sonar.projectKey=NguyenVu04_track-nest
sonar.projectName=track-nest
sonar.projectVersion=1.0
sonar.organization=nguyenvu04

sonar.sources=\
  service/criminal-reports/src/main/java/project/tracknest/criminalreports/controller,\
  service/criminal-reports/src/main/java/project/tracknest/criminalreports/domain,\
  service/emergency-ops/src/main/java/project/tracknest/emergencyops/controller,\
  service/emergency-ops/src/main/java/project/tracknest/emergencyops/domain,\
  service/user-tracking/src/main/java/project/tracknest/usertracking/controller,\
  service/user-tracking/src/main/java/project/tracknest/usertracking/domain,\
  frontend/track-nest-web/app,\
  frontend/track-nest-web/components,\
  frontend/track-nest-web/contexts,\
  frontend/track-nest-web/services,\
  frontend/track-nest-web/types,\
  frontend/TrackNest/app,\
  frontend/TrackNest/components,\
  frontend/TrackNest/services,\
  frontend/TrackNest/hooks,\
  frontend/TrackNest/utils,\
  frontend/TrackNest/contexts

sonar.tests=\
  service/criminal-reports/src/test/java,\
  service/emergency-ops/src/test/java,\
  service/user-tracking/src/test/java

sonar.exclusions=\
  **/node_modules/**,\
  **/.next/**,\
  **/build/generated/**,\
  **/android/**,\
  **/.expo/**,\
  **/public/**,\
  **/assets/**,\
  **/*.test.ts,\
  **/*.test.tsx,\
  **/*.spec.ts,\
  **/*.spec.tsx,\
  **/__tests__/**

sonar.java.binaries=\
  service/criminal-reports/build/classes/java/main,\
  service/emergency-ops/build/classes/java/main,\
  service/user-tracking/build/classes/java/main

sonar.java.test.binaries=\
  service/criminal-reports/build/classes/java/test,\
  service/emergency-ops/build/classes/java/test,\
  service/user-tracking/build/classes/java/test

sonar.java.source=25
sonar.java.target=25

sonar.coverage.jacoco.xmlReportPaths=\
  service/criminal-reports/build/reports/jacoco/test/jacocoTestReport.xml,\
  service/emergency-ops/build/reports/jacoco/test/jacocoTestReport.xml,\
  service/user-tracking/build/reports/jacoco/test/jacocoTestReport.xml

sonar.javascript.lcov.reportPaths=\
  frontend/TrackNest/coverage/lcov.info,\
  frontend/track-nest-web/coverage/lcov.info