{{- if .Values.criminalreports.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: criminal-reports
spec:
  selector:
    app: criminal-reports
  ports:
  - port: 8080
    targetPort: 8080
{{- end }}