{{- if .Values.iam.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: iam
spec:
  replicas: 1
  selector:
    matchLabels:
      app: iam
  template:
    metadata:
      labels:
        app: iam
    spec:
      containers:
      - name: iam
        image: {{ .Values.iam.image }}
        ports:
        - containerPort: 8080
        env:
        - name: KC_DB_VENDOR
          value: {{ .Values.iam.db-vendor }}
        - name: KC_DB_USERNAME
          value: {{ .Values.iam.db-username }}
        - name: KC_DB_PASSWORD
          value: {{ .Values.iam.db-password }}
        - name: KC_DB_URL
          value: {{ .Values.iam.db-url }}
        resources:
          requests:
            memory: "64Mi"
            cpu: "25m"
          limits:
            memory: "128Mi"
            cpu: "500m"
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
{{- end }}