apiVersion: apisix.apache.org/v2
kind: ApisixRoute
metadata:
  name: ingress-controller
spec:
  http:
  - name: "user-tracking"
    match:
      paths:
      - "/user-tracking"
    backends:
    - serviceName: user-tracking
      servicePort: 8000