/**
 * @fileoverview gRPC-Web generated client stub for project.tracknest.usertracking.proto.v1
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v2.0.2
// 	protoc              v6.33.2
// source: familymessenger.proto


/* eslint-disable */
// @ts-nocheck


import * as grpcWeb from 'grpc-web';

import * as familymessenger_pb from './familymessenger_pb'; // proto import: "familymessenger.proto"


export class FamilyMessengerControllerClient {
  client_: grpcWeb.AbstractClientBase;
  hostname_: string;
  credentials_: null | { [index: string]: string; };
  options_: null | { [index: string]: any; };

  constructor (hostname: string,
               credentials?: null | { [index: string]: string; },
               options?: null | { [index: string]: any; }) {
    if (!options) options = {};
    if (!credentials) credentials = {};
    options['format'] = 'text';

    this.client_ = new grpcWeb.GrpcWebClientBase(options);
    this.hostname_ = hostname.replace(/\/+$/, '');
    this.credentials_ = credentials;
    this.options_ = options;
  }

  methodDescriptorSendMessage = new grpcWeb.MethodDescriptor(
    '/project.tracknest.usertracking.proto.v1.FamilyMessengerController/SendMessage',
    grpcWeb.MethodType.UNARY,
    familymessenger_pb.SendMessageRequest,
    familymessenger_pb.SendMessageResponse,
    (request: familymessenger_pb.SendMessageRequest) => {
      return request.serializeBinary();
    },
    familymessenger_pb.SendMessageResponse.deserializeBinary
  );

  sendMessage(
    request: familymessenger_pb.SendMessageRequest,
    metadata?: grpcWeb.Metadata | null): Promise<familymessenger_pb.SendMessageResponse>;

  sendMessage(
    request: familymessenger_pb.SendMessageRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: familymessenger_pb.SendMessageResponse) => void): grpcWeb.ClientReadableStream<familymessenger_pb.SendMessageResponse>;

  sendMessage(
    request: familymessenger_pb.SendMessageRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: familymessenger_pb.SendMessageResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/project.tracknest.usertracking.proto.v1.FamilyMessengerController/SendMessage',
        request,
        metadata || {},
        this.methodDescriptorSendMessage,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/project.tracknest.usertracking.proto.v1.FamilyMessengerController/SendMessage',
    request,
    metadata || {},
    this.methodDescriptorSendMessage);
  }

  methodDescriptorListMessages = new grpcWeb.MethodDescriptor(
    '/project.tracknest.usertracking.proto.v1.FamilyMessengerController/ListMessages',
    grpcWeb.MethodType.UNARY,
    familymessenger_pb.ListMessagesRequest,
    familymessenger_pb.ListMessagesResponse,
    (request: familymessenger_pb.ListMessagesRequest) => {
      return request.serializeBinary();
    },
    familymessenger_pb.ListMessagesResponse.deserializeBinary
  );

  listMessages(
    request: familymessenger_pb.ListMessagesRequest,
    metadata?: grpcWeb.Metadata | null): Promise<familymessenger_pb.ListMessagesResponse>;

  listMessages(
    request: familymessenger_pb.ListMessagesRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: familymessenger_pb.ListMessagesResponse) => void): grpcWeb.ClientReadableStream<familymessenger_pb.ListMessagesResponse>;

  listMessages(
    request: familymessenger_pb.ListMessagesRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: familymessenger_pb.ListMessagesResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/project.tracknest.usertracking.proto.v1.FamilyMessengerController/ListMessages',
        request,
        metadata || {},
        this.methodDescriptorListMessages,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/project.tracknest.usertracking.proto.v1.FamilyMessengerController/ListMessages',
    request,
    metadata || {},
    this.methodDescriptorListMessages);
  }

  methodDescriptorReceiveMessageStream = new grpcWeb.MethodDescriptor(
    '/project.tracknest.usertracking.proto.v1.FamilyMessengerController/ReceiveMessageStream',
    grpcWeb.MethodType.SERVER_STREAMING,
    familymessenger_pb.ReceiveMessageStreamRequest,
    familymessenger_pb.Message,
    (request: familymessenger_pb.ReceiveMessageStreamRequest) => {
      return request.serializeBinary();
    },
    familymessenger_pb.Message.deserializeBinary
  );

  receiveMessageStream(
    request: familymessenger_pb.ReceiveMessageStreamRequest,
    metadata?: grpcWeb.Metadata): grpcWeb.ClientReadableStream<familymessenger_pb.Message> {
    return this.client_.serverStreaming(
      this.hostname_ +
        '/project.tracknest.usertracking.proto.v1.FamilyMessengerController/ReceiveMessageStream',
      request,
      metadata || {},
      this.methodDescriptorReceiveMessageStream);
  }

}

