/**
 * @fileoverview gRPC-Web generated client stub for project.tracknest.usertracking.proto.v1
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v2.0.2
// 	protoc              v6.33.2
// source: notifier.proto


/* eslint-disable */
// @ts-nocheck


import * as grpcWeb from 'grpc-web';

import * as notifier_pb from './notifier_pb'; // proto import: "notifier.proto"


export class NotifierControllerClient {
  client_: grpcWeb.AbstractClientBase;
  hostname_: string;
  credentials_: null | { [index: string]: string; };
  options_: null | { [index: string]: any; };

  constructor (hostname: string,
               credentials?: null | { [index: string]: string; },
               options?: null | { [index: string]: any; }) {
    if (!options) options = {};
    if (!credentials) credentials = {};
    options['format'] = 'text';

    this.client_ = new grpcWeb.GrpcWebClientBase(options);
    this.hostname_ = hostname.replace(/\/+$/, '');
    this.credentials_ = credentials;
    this.options_ = options;
  }

  methodDescriptorRegisterMobileDevice = new grpcWeb.MethodDescriptor(
    '/project.tracknest.usertracking.proto.v1.NotifierController/RegisterMobileDevice',
    grpcWeb.MethodType.UNARY,
    notifier_pb.RegisterMobileDeviceRequest,
    notifier_pb.RegisterMobileDeviceResponse,
    (request: notifier_pb.RegisterMobileDeviceRequest) => {
      return request.serializeBinary();
    },
    notifier_pb.RegisterMobileDeviceResponse.deserializeBinary
  );

  registerMobileDevice(
    request: notifier_pb.RegisterMobileDeviceRequest,
    metadata?: grpcWeb.Metadata | null): Promise<notifier_pb.RegisterMobileDeviceResponse>;

  registerMobileDevice(
    request: notifier_pb.RegisterMobileDeviceRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: notifier_pb.RegisterMobileDeviceResponse) => void): grpcWeb.ClientReadableStream<notifier_pb.RegisterMobileDeviceResponse>;

  registerMobileDevice(
    request: notifier_pb.RegisterMobileDeviceRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: notifier_pb.RegisterMobileDeviceResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/project.tracknest.usertracking.proto.v1.NotifierController/RegisterMobileDevice',
        request,
        metadata || {},
        this.methodDescriptorRegisterMobileDevice,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/project.tracknest.usertracking.proto.v1.NotifierController/RegisterMobileDevice',
    request,
    metadata || {},
    this.methodDescriptorRegisterMobileDevice);
  }

  methodDescriptorUpdateMobileDevice = new grpcWeb.MethodDescriptor(
    '/project.tracknest.usertracking.proto.v1.NotifierController/UpdateMobileDevice',
    grpcWeb.MethodType.UNARY,
    notifier_pb.UpdateMobileDeviceRequest,
    notifier_pb.UpdateMobileDeviceResponse,
    (request: notifier_pb.UpdateMobileDeviceRequest) => {
      return request.serializeBinary();
    },
    notifier_pb.UpdateMobileDeviceResponse.deserializeBinary
  );

  updateMobileDevice(
    request: notifier_pb.UpdateMobileDeviceRequest,
    metadata?: grpcWeb.Metadata | null): Promise<notifier_pb.UpdateMobileDeviceResponse>;

  updateMobileDevice(
    request: notifier_pb.UpdateMobileDeviceRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: notifier_pb.UpdateMobileDeviceResponse) => void): grpcWeb.ClientReadableStream<notifier_pb.UpdateMobileDeviceResponse>;

  updateMobileDevice(
    request: notifier_pb.UpdateMobileDeviceRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: notifier_pb.UpdateMobileDeviceResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/project.tracknest.usertracking.proto.v1.NotifierController/UpdateMobileDevice',
        request,
        metadata || {},
        this.methodDescriptorUpdateMobileDevice,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/project.tracknest.usertracking.proto.v1.NotifierController/UpdateMobileDevice',
    request,
    metadata || {},
    this.methodDescriptorUpdateMobileDevice);
  }

  methodDescriptorUnregisterMobileDevice = new grpcWeb.MethodDescriptor(
    '/project.tracknest.usertracking.proto.v1.NotifierController/UnregisterMobileDevice',
    grpcWeb.MethodType.UNARY,
    notifier_pb.UnregisterMobileDeviceRequest,
    notifier_pb.UnregisterMobileDeviceResponse,
    (request: notifier_pb.UnregisterMobileDeviceRequest) => {
      return request.serializeBinary();
    },
    notifier_pb.UnregisterMobileDeviceResponse.deserializeBinary
  );

  unregisterMobileDevice(
    request: notifier_pb.UnregisterMobileDeviceRequest,
    metadata?: grpcWeb.Metadata | null): Promise<notifier_pb.UnregisterMobileDeviceResponse>;

  unregisterMobileDevice(
    request: notifier_pb.UnregisterMobileDeviceRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: notifier_pb.UnregisterMobileDeviceResponse) => void): grpcWeb.ClientReadableStream<notifier_pb.UnregisterMobileDeviceResponse>;

  unregisterMobileDevice(
    request: notifier_pb.UnregisterMobileDeviceRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: notifier_pb.UnregisterMobileDeviceResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/project.tracknest.usertracking.proto.v1.NotifierController/UnregisterMobileDevice',
        request,
        metadata || {},
        this.methodDescriptorUnregisterMobileDevice,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/project.tracknest.usertracking.proto.v1.NotifierController/UnregisterMobileDevice',
    request,
    metadata || {},
    this.methodDescriptorUnregisterMobileDevice);
  }

  methodDescriptorListTrackingNotifications = new grpcWeb.MethodDescriptor(
    '/project.tracknest.usertracking.proto.v1.NotifierController/ListTrackingNotifications',
    grpcWeb.MethodType.UNARY,
    notifier_pb.ListTrackingNotificationsRequest,
    notifier_pb.ListTrackingNotificationsResponse,
    (request: notifier_pb.ListTrackingNotificationsRequest) => {
      return request.serializeBinary();
    },
    notifier_pb.ListTrackingNotificationsResponse.deserializeBinary
  );

  listTrackingNotifications(
    request: notifier_pb.ListTrackingNotificationsRequest,
    metadata?: grpcWeb.Metadata | null): Promise<notifier_pb.ListTrackingNotificationsResponse>;

  listTrackingNotifications(
    request: notifier_pb.ListTrackingNotificationsRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: notifier_pb.ListTrackingNotificationsResponse) => void): grpcWeb.ClientReadableStream<notifier_pb.ListTrackingNotificationsResponse>;

  listTrackingNotifications(
    request: notifier_pb.ListTrackingNotificationsRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: notifier_pb.ListTrackingNotificationsResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/project.tracknest.usertracking.proto.v1.NotifierController/ListTrackingNotifications',
        request,
        metadata || {},
        this.methodDescriptorListTrackingNotifications,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/project.tracknest.usertracking.proto.v1.NotifierController/ListTrackingNotifications',
    request,
    metadata || {},
    this.methodDescriptorListTrackingNotifications);
  }

  methodDescriptorListRiskNotifications = new grpcWeb.MethodDescriptor(
    '/project.tracknest.usertracking.proto.v1.NotifierController/ListRiskNotifications',
    grpcWeb.MethodType.UNARY,
    notifier_pb.ListRiskNotificationsRequest,
    notifier_pb.ListRiskNotificationsResponse,
    (request: notifier_pb.ListRiskNotificationsRequest) => {
      return request.serializeBinary();
    },
    notifier_pb.ListRiskNotificationsResponse.deserializeBinary
  );

  listRiskNotifications(
    request: notifier_pb.ListRiskNotificationsRequest,
    metadata?: grpcWeb.Metadata | null): Promise<notifier_pb.ListRiskNotificationsResponse>;

  listRiskNotifications(
    request: notifier_pb.ListRiskNotificationsRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: notifier_pb.ListRiskNotificationsResponse) => void): grpcWeb.ClientReadableStream<notifier_pb.ListRiskNotificationsResponse>;

  listRiskNotifications(
    request: notifier_pb.ListRiskNotificationsRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: notifier_pb.ListRiskNotificationsResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/project.tracknest.usertracking.proto.v1.NotifierController/ListRiskNotifications',
        request,
        metadata || {},
        this.methodDescriptorListRiskNotifications,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/project.tracknest.usertracking.proto.v1.NotifierController/ListRiskNotifications',
    request,
    metadata || {},
    this.methodDescriptorListRiskNotifications);
  }

  methodDescriptorDeleteTrackingNotification = new grpcWeb.MethodDescriptor(
    '/project.tracknest.usertracking.proto.v1.NotifierController/DeleteTrackingNotification',
    grpcWeb.MethodType.UNARY,
    notifier_pb.DeleteTrackingNotificationRequest,
    notifier_pb.DeleteTrackingNotificationResponse,
    (request: notifier_pb.DeleteTrackingNotificationRequest) => {
      return request.serializeBinary();
    },
    notifier_pb.DeleteTrackingNotificationResponse.deserializeBinary
  );

  deleteTrackingNotification(
    request: notifier_pb.DeleteTrackingNotificationRequest,
    metadata?: grpcWeb.Metadata | null): Promise<notifier_pb.DeleteTrackingNotificationResponse>;

  deleteTrackingNotification(
    request: notifier_pb.DeleteTrackingNotificationRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: notifier_pb.DeleteTrackingNotificationResponse) => void): grpcWeb.ClientReadableStream<notifier_pb.DeleteTrackingNotificationResponse>;

  deleteTrackingNotification(
    request: notifier_pb.DeleteTrackingNotificationRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: notifier_pb.DeleteTrackingNotificationResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/project.tracknest.usertracking.proto.v1.NotifierController/DeleteTrackingNotification',
        request,
        metadata || {},
        this.methodDescriptorDeleteTrackingNotification,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/project.tracknest.usertracking.proto.v1.NotifierController/DeleteTrackingNotification',
    request,
    metadata || {},
    this.methodDescriptorDeleteTrackingNotification);
  }

  methodDescriptorDeleteRiskNotification = new grpcWeb.MethodDescriptor(
    '/project.tracknest.usertracking.proto.v1.NotifierController/DeleteRiskNotification',
    grpcWeb.MethodType.UNARY,
    notifier_pb.DeleteRiskNotificationRequest,
    notifier_pb.DeleteRiskNotificationResponse,
    (request: notifier_pb.DeleteRiskNotificationRequest) => {
      return request.serializeBinary();
    },
    notifier_pb.DeleteRiskNotificationResponse.deserializeBinary
  );

  deleteRiskNotification(
    request: notifier_pb.DeleteRiskNotificationRequest,
    metadata?: grpcWeb.Metadata | null): Promise<notifier_pb.DeleteRiskNotificationResponse>;

  deleteRiskNotification(
    request: notifier_pb.DeleteRiskNotificationRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: notifier_pb.DeleteRiskNotificationResponse) => void): grpcWeb.ClientReadableStream<notifier_pb.DeleteRiskNotificationResponse>;

  deleteRiskNotification(
    request: notifier_pb.DeleteRiskNotificationRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: notifier_pb.DeleteRiskNotificationResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/project.tracknest.usertracking.proto.v1.NotifierController/DeleteRiskNotification',
        request,
        metadata || {},
        this.methodDescriptorDeleteRiskNotification,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/project.tracknest.usertracking.proto.v1.NotifierController/DeleteRiskNotification',
    request,
    metadata || {},
    this.methodDescriptorDeleteRiskNotification);
  }

  methodDescriptorDeleteTrackingNotifications = new grpcWeb.MethodDescriptor(
    '/project.tracknest.usertracking.proto.v1.NotifierController/DeleteTrackingNotifications',
    grpcWeb.MethodType.UNARY,
    notifier_pb.DeleteTrackingNotificationsRequest,
    notifier_pb.DeleteTrackingNotificationsResponse,
    (request: notifier_pb.DeleteTrackingNotificationsRequest) => {
      return request.serializeBinary();
    },
    notifier_pb.DeleteTrackingNotificationsResponse.deserializeBinary
  );

  deleteTrackingNotifications(
    request: notifier_pb.DeleteTrackingNotificationsRequest,
    metadata?: grpcWeb.Metadata | null): Promise<notifier_pb.DeleteTrackingNotificationsResponse>;

  deleteTrackingNotifications(
    request: notifier_pb.DeleteTrackingNotificationsRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: notifier_pb.DeleteTrackingNotificationsResponse) => void): grpcWeb.ClientReadableStream<notifier_pb.DeleteTrackingNotificationsResponse>;

  deleteTrackingNotifications(
    request: notifier_pb.DeleteTrackingNotificationsRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: notifier_pb.DeleteTrackingNotificationsResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/project.tracknest.usertracking.proto.v1.NotifierController/DeleteTrackingNotifications',
        request,
        metadata || {},
        this.methodDescriptorDeleteTrackingNotifications,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/project.tracknest.usertracking.proto.v1.NotifierController/DeleteTrackingNotifications',
    request,
    metadata || {},
    this.methodDescriptorDeleteTrackingNotifications);
  }

  methodDescriptordeleteRiskNotifications = new grpcWeb.MethodDescriptor(
    '/project.tracknest.usertracking.proto.v1.NotifierController/deleteRiskNotifications',
    grpcWeb.MethodType.UNARY,
    notifier_pb.DeleteRiskNotificationsRequest,
    notifier_pb.DeleteRiskNotificationsResponse,
    (request: notifier_pb.DeleteRiskNotificationsRequest) => {
      return request.serializeBinary();
    },
    notifier_pb.DeleteRiskNotificationsResponse.deserializeBinary
  );

  deleteRiskNotifications(
    request: notifier_pb.DeleteRiskNotificationsRequest,
    metadata?: grpcWeb.Metadata | null): Promise<notifier_pb.DeleteRiskNotificationsResponse>;

  deleteRiskNotifications(
    request: notifier_pb.DeleteRiskNotificationsRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: notifier_pb.DeleteRiskNotificationsResponse) => void): grpcWeb.ClientReadableStream<notifier_pb.DeleteRiskNotificationsResponse>;

  deleteRiskNotifications(
    request: notifier_pb.DeleteRiskNotificationsRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: notifier_pb.DeleteRiskNotificationsResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/project.tracknest.usertracking.proto.v1.NotifierController/deleteRiskNotifications',
        request,
        metadata || {},
        this.methodDescriptordeleteRiskNotifications,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/project.tracknest.usertracking.proto.v1.NotifierController/deleteRiskNotifications',
    request,
    metadata || {},
    this.methodDescriptordeleteRiskNotifications);
  }

  methodDescriptorClearTrackingNotifications = new grpcWeb.MethodDescriptor(
    '/project.tracknest.usertracking.proto.v1.NotifierController/ClearTrackingNotifications',
    grpcWeb.MethodType.UNARY,
    notifier_pb.ClearTrackingNotificationsRequest,
    notifier_pb.ClearTrackingNotificationsResponse,
    (request: notifier_pb.ClearTrackingNotificationsRequest) => {
      return request.serializeBinary();
    },
    notifier_pb.ClearTrackingNotificationsResponse.deserializeBinary
  );

  clearTrackingNotifications(
    request: notifier_pb.ClearTrackingNotificationsRequest,
    metadata?: grpcWeb.Metadata | null): Promise<notifier_pb.ClearTrackingNotificationsResponse>;

  clearTrackingNotifications(
    request: notifier_pb.ClearTrackingNotificationsRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: notifier_pb.ClearTrackingNotificationsResponse) => void): grpcWeb.ClientReadableStream<notifier_pb.ClearTrackingNotificationsResponse>;

  clearTrackingNotifications(
    request: notifier_pb.ClearTrackingNotificationsRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: notifier_pb.ClearTrackingNotificationsResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/project.tracknest.usertracking.proto.v1.NotifierController/ClearTrackingNotifications',
        request,
        metadata || {},
        this.methodDescriptorClearTrackingNotifications,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/project.tracknest.usertracking.proto.v1.NotifierController/ClearTrackingNotifications',
    request,
    metadata || {},
    this.methodDescriptorClearTrackingNotifications);
  }

  methodDescriptorClearRiskNotifications = new grpcWeb.MethodDescriptor(
    '/project.tracknest.usertracking.proto.v1.NotifierController/ClearRiskNotifications',
    grpcWeb.MethodType.UNARY,
    notifier_pb.ClearRiskNotificationsRequest,
    notifier_pb.ClearRiskNotificationsResponse,
    (request: notifier_pb.ClearRiskNotificationsRequest) => {
      return request.serializeBinary();
    },
    notifier_pb.ClearRiskNotificationsResponse.deserializeBinary
  );

  clearRiskNotifications(
    request: notifier_pb.ClearRiskNotificationsRequest,
    metadata?: grpcWeb.Metadata | null): Promise<notifier_pb.ClearRiskNotificationsResponse>;

  clearRiskNotifications(
    request: notifier_pb.ClearRiskNotificationsRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: notifier_pb.ClearRiskNotificationsResponse) => void): grpcWeb.ClientReadableStream<notifier_pb.ClearRiskNotificationsResponse>;

  clearRiskNotifications(
    request: notifier_pb.ClearRiskNotificationsRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: notifier_pb.ClearRiskNotificationsResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/project.tracknest.usertracking.proto.v1.NotifierController/ClearRiskNotifications',
        request,
        metadata || {},
        this.methodDescriptorClearRiskNotifications,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/project.tracknest.usertracking.proto.v1.NotifierController/ClearRiskNotifications',
    request,
    metadata || {},
    this.methodDescriptorClearRiskNotifications);
  }

  methodDescriptorCountTrackingNotifications = new grpcWeb.MethodDescriptor(
    '/project.tracknest.usertracking.proto.v1.NotifierController/CountTrackingNotifications',
    grpcWeb.MethodType.UNARY,
    notifier_pb.CountTrackingNotificationsRequest,
    notifier_pb.CountTrackingNotificationsResponse,
    (request: notifier_pb.CountTrackingNotificationsRequest) => {
      return request.serializeBinary();
    },
    notifier_pb.CountTrackingNotificationsResponse.deserializeBinary
  );

  countTrackingNotifications(
    request: notifier_pb.CountTrackingNotificationsRequest,
    metadata?: grpcWeb.Metadata | null): Promise<notifier_pb.CountTrackingNotificationsResponse>;

  countTrackingNotifications(
    request: notifier_pb.CountTrackingNotificationsRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: notifier_pb.CountTrackingNotificationsResponse) => void): grpcWeb.ClientReadableStream<notifier_pb.CountTrackingNotificationsResponse>;

  countTrackingNotifications(
    request: notifier_pb.CountTrackingNotificationsRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: notifier_pb.CountTrackingNotificationsResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/project.tracknest.usertracking.proto.v1.NotifierController/CountTrackingNotifications',
        request,
        metadata || {},
        this.methodDescriptorCountTrackingNotifications,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/project.tracknest.usertracking.proto.v1.NotifierController/CountTrackingNotifications',
    request,
    metadata || {},
    this.methodDescriptorCountTrackingNotifications);
  }

  methodDescriptorCountRiskNotifications = new grpcWeb.MethodDescriptor(
    '/project.tracknest.usertracking.proto.v1.NotifierController/CountRiskNotifications',
    grpcWeb.MethodType.UNARY,
    notifier_pb.CountRiskNotificationsRequest,
    notifier_pb.CountRiskNotificationsResponse,
    (request: notifier_pb.CountRiskNotificationsRequest) => {
      return request.serializeBinary();
    },
    notifier_pb.CountRiskNotificationsResponse.deserializeBinary
  );

  countRiskNotifications(
    request: notifier_pb.CountRiskNotificationsRequest,
    metadata?: grpcWeb.Metadata | null): Promise<notifier_pb.CountRiskNotificationsResponse>;

  countRiskNotifications(
    request: notifier_pb.CountRiskNotificationsRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: notifier_pb.CountRiskNotificationsResponse) => void): grpcWeb.ClientReadableStream<notifier_pb.CountRiskNotificationsResponse>;

  countRiskNotifications(
    request: notifier_pb.CountRiskNotificationsRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: notifier_pb.CountRiskNotificationsResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/project.tracknest.usertracking.proto.v1.NotifierController/CountRiskNotifications',
        request,
        metadata || {},
        this.methodDescriptorCountRiskNotifications,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/project.tracknest.usertracking.proto.v1.NotifierController/CountRiskNotifications',
    request,
    metadata || {},
    this.methodDescriptorCountRiskNotifications);
  }

}

