// source: notifier.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = globalThis;

var google_protobuf_empty_pb = require('google-protobuf/google/protobuf/empty_pb.js');
goog.object.extend(proto, google_protobuf_empty_pb);
var google_protobuf_wrappers_pb = require('google-protobuf/google/protobuf/wrappers_pb.js');
goog.object.extend(proto, google_protobuf_wrappers_pb);
goog.exportSymbol('proto.project.tracknest.usertracking.proto.MobileDeviceRequest', null, global);
goog.exportSymbol('proto.project.tracknest.usertracking.proto.NotificationIds', null, global);
goog.exportSymbol('proto.project.tracknest.usertracking.proto.RiskNotificationResponse', null, global);
goog.exportSymbol('proto.project.tracknest.usertracking.proto.TrackingNotificationResponse', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.project.tracknest.usertracking.proto.NotificationIds = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.project.tracknest.usertracking.proto.NotificationIds.repeatedFields_, null);
};
goog.inherits(proto.project.tracknest.usertracking.proto.NotificationIds, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.project.tracknest.usertracking.proto.NotificationIds.displayName = 'proto.project.tracknest.usertracking.proto.NotificationIds';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.project.tracknest.usertracking.proto.MobileDeviceRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.project.tracknest.usertracking.proto.MobileDeviceRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.project.tracknest.usertracking.proto.MobileDeviceRequest.displayName = 'proto.project.tracknest.usertracking.proto.MobileDeviceRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.project.tracknest.usertracking.proto.TrackingNotificationResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.project.tracknest.usertracking.proto.TrackingNotificationResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.project.tracknest.usertracking.proto.TrackingNotificationResponse.displayName = 'proto.project.tracknest.usertracking.proto.TrackingNotificationResponse';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.project.tracknest.usertracking.proto.RiskNotificationResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.project.tracknest.usertracking.proto.RiskNotificationResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.project.tracknest.usertracking.proto.RiskNotificationResponse.displayName = 'proto.project.tracknest.usertracking.proto.RiskNotificationResponse';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.project.tracknest.usertracking.proto.NotificationIds.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.project.tracknest.usertracking.proto.NotificationIds.prototype.toObject = function(opt_includeInstance) {
  return proto.project.tracknest.usertracking.proto.NotificationIds.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.project.tracknest.usertracking.proto.NotificationIds} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.project.tracknest.usertracking.proto.NotificationIds.toObject = function(includeInstance, msg) {
  var f, obj = {
idsList: (f = jspb.Message.getRepeatedField(msg, 1)) == null ? undefined : f
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.binary.bytesource.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.project.tracknest.usertracking.proto.NotificationIds}
 */
proto.project.tracknest.usertracking.proto.NotificationIds.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.project.tracknest.usertracking.proto.NotificationIds;
  return proto.project.tracknest.usertracking.proto.NotificationIds.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.project.tracknest.usertracking.proto.NotificationIds} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.project.tracknest.usertracking.proto.NotificationIds}
 */
proto.project.tracknest.usertracking.proto.NotificationIds.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readStringRequireUtf8());
      msg.addIds(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.project.tracknest.usertracking.proto.NotificationIds.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.project.tracknest.usertracking.proto.NotificationIds.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.project.tracknest.usertracking.proto.NotificationIds} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.project.tracknest.usertracking.proto.NotificationIds.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getIdsList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      1,
      f
    );
  }
};


/**
 * repeated string ids = 1;
 * @return {!Array<string>}
 */
proto.project.tracknest.usertracking.proto.NotificationIds.prototype.getIdsList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 1));
};


/**
 * @param {!Array<string>} value
 * @return {!proto.project.tracknest.usertracking.proto.NotificationIds} returns this
 */
proto.project.tracknest.usertracking.proto.NotificationIds.prototype.setIdsList = function(value) {
  return jspb.Message.setField(this, 1, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 * @return {!proto.project.tracknest.usertracking.proto.NotificationIds} returns this
 */
proto.project.tracknest.usertracking.proto.NotificationIds.prototype.addIds = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 1, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.project.tracknest.usertracking.proto.NotificationIds} returns this
 */
proto.project.tracknest.usertracking.proto.NotificationIds.prototype.clearIdsList = function() {
  return this.setIdsList([]);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.project.tracknest.usertracking.proto.MobileDeviceRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.project.tracknest.usertracking.proto.MobileDeviceRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.project.tracknest.usertracking.proto.MobileDeviceRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.project.tracknest.usertracking.proto.MobileDeviceRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
devicetoken: jspb.Message.getFieldWithDefault(msg, 1, ""),
languagecode: jspb.Message.getFieldWithDefault(msg, 2, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.binary.bytesource.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.project.tracknest.usertracking.proto.MobileDeviceRequest}
 */
proto.project.tracknest.usertracking.proto.MobileDeviceRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.project.tracknest.usertracking.proto.MobileDeviceRequest;
  return proto.project.tracknest.usertracking.proto.MobileDeviceRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.project.tracknest.usertracking.proto.MobileDeviceRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.project.tracknest.usertracking.proto.MobileDeviceRequest}
 */
proto.project.tracknest.usertracking.proto.MobileDeviceRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readStringRequireUtf8());
      msg.setDevicetoken(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readStringRequireUtf8());
      msg.setLanguagecode(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.project.tracknest.usertracking.proto.MobileDeviceRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.project.tracknest.usertracking.proto.MobileDeviceRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.project.tracknest.usertracking.proto.MobileDeviceRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.project.tracknest.usertracking.proto.MobileDeviceRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getDevicetoken();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getLanguagecode();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
};


/**
 * optional string deviceToken = 1;
 * @return {string}
 */
proto.project.tracknest.usertracking.proto.MobileDeviceRequest.prototype.getDevicetoken = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.project.tracknest.usertracking.proto.MobileDeviceRequest} returns this
 */
proto.project.tracknest.usertracking.proto.MobileDeviceRequest.prototype.setDevicetoken = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string languageCode = 2;
 * @return {string}
 */
proto.project.tracknest.usertracking.proto.MobileDeviceRequest.prototype.getLanguagecode = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.project.tracknest.usertracking.proto.MobileDeviceRequest} returns this
 */
proto.project.tracknest.usertracking.proto.MobileDeviceRequest.prototype.setLanguagecode = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.project.tracknest.usertracking.proto.TrackingNotificationResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.project.tracknest.usertracking.proto.TrackingNotificationResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.project.tracknest.usertracking.proto.TrackingNotificationResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.project.tracknest.usertracking.proto.TrackingNotificationResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
id: jspb.Message.getFieldWithDefault(msg, 1, ""),
trackerid: jspb.Message.getFieldWithDefault(msg, 2, ""),
trackerusername: jspb.Message.getFieldWithDefault(msg, 3, ""),
targetid: jspb.Message.getFieldWithDefault(msg, 4, ""),
targetusername: jspb.Message.getFieldWithDefault(msg, 5, ""),
createdat: jspb.Message.getFieldWithDefault(msg, 6, 0),
title: jspb.Message.getFieldWithDefault(msg, 7, ""),
content: jspb.Message.getFieldWithDefault(msg, 8, ""),
seen: jspb.Message.getBooleanFieldWithDefault(msg, 9, false)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.binary.bytesource.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.project.tracknest.usertracking.proto.TrackingNotificationResponse}
 */
proto.project.tracknest.usertracking.proto.TrackingNotificationResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.project.tracknest.usertracking.proto.TrackingNotificationResponse;
  return proto.project.tracknest.usertracking.proto.TrackingNotificationResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.project.tracknest.usertracking.proto.TrackingNotificationResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.project.tracknest.usertracking.proto.TrackingNotificationResponse}
 */
proto.project.tracknest.usertracking.proto.TrackingNotificationResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readStringRequireUtf8());
      msg.setId(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readStringRequireUtf8());
      msg.setTrackerid(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readStringRequireUtf8());
      msg.setTrackerusername(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readStringRequireUtf8());
      msg.setTargetid(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readStringRequireUtf8());
      msg.setTargetusername(value);
      break;
    case 6:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setCreatedat(value);
      break;
    case 7:
      var value = /** @type {string} */ (reader.readStringRequireUtf8());
      msg.setTitle(value);
      break;
    case 8:
      var value = /** @type {string} */ (reader.readStringRequireUtf8());
      msg.setContent(value);
      break;
    case 9:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setSeen(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.project.tracknest.usertracking.proto.TrackingNotificationResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.project.tracknest.usertracking.proto.TrackingNotificationResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.project.tracknest.usertracking.proto.TrackingNotificationResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.project.tracknest.usertracking.proto.TrackingNotificationResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getTrackerid();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getTrackerusername();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getTargetid();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getTargetusername();
  if (f.length > 0) {
    writer.writeString(
      5,
      f
    );
  }
  f = message.getCreatedat();
  if (f !== 0) {
    writer.writeUint64(
      6,
      f
    );
  }
  f = message.getTitle();
  if (f.length > 0) {
    writer.writeString(
      7,
      f
    );
  }
  f = message.getContent();
  if (f.length > 0) {
    writer.writeString(
      8,
      f
    );
  }
  f = message.getSeen();
  if (f) {
    writer.writeBool(
      9,
      f
    );
  }
};


/**
 * optional string id = 1;
 * @return {string}
 */
proto.project.tracknest.usertracking.proto.TrackingNotificationResponse.prototype.getId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.project.tracknest.usertracking.proto.TrackingNotificationResponse} returns this
 */
proto.project.tracknest.usertracking.proto.TrackingNotificationResponse.prototype.setId = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string trackerId = 2;
 * @return {string}
 */
proto.project.tracknest.usertracking.proto.TrackingNotificationResponse.prototype.getTrackerid = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.project.tracknest.usertracking.proto.TrackingNotificationResponse} returns this
 */
proto.project.tracknest.usertracking.proto.TrackingNotificationResponse.prototype.setTrackerid = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string trackerUsername = 3;
 * @return {string}
 */
proto.project.tracknest.usertracking.proto.TrackingNotificationResponse.prototype.getTrackerusername = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.project.tracknest.usertracking.proto.TrackingNotificationResponse} returns this
 */
proto.project.tracknest.usertracking.proto.TrackingNotificationResponse.prototype.setTrackerusername = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional string targetId = 4;
 * @return {string}
 */
proto.project.tracknest.usertracking.proto.TrackingNotificationResponse.prototype.getTargetid = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * @param {string} value
 * @return {!proto.project.tracknest.usertracking.proto.TrackingNotificationResponse} returns this
 */
proto.project.tracknest.usertracking.proto.TrackingNotificationResponse.prototype.setTargetid = function(value) {
  return jspb.Message.setProto3StringField(this, 4, value);
};


/**
 * optional string targetUsername = 5;
 * @return {string}
 */
proto.project.tracknest.usertracking.proto.TrackingNotificationResponse.prototype.getTargetusername = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/**
 * @param {string} value
 * @return {!proto.project.tracknest.usertracking.proto.TrackingNotificationResponse} returns this
 */
proto.project.tracknest.usertracking.proto.TrackingNotificationResponse.prototype.setTargetusername = function(value) {
  return jspb.Message.setProto3StringField(this, 5, value);
};


/**
 * optional uint64 createdAt = 6;
 * @return {number}
 */
proto.project.tracknest.usertracking.proto.TrackingNotificationResponse.prototype.getCreatedat = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 6, 0));
};


/**
 * @param {number} value
 * @return {!proto.project.tracknest.usertracking.proto.TrackingNotificationResponse} returns this
 */
proto.project.tracknest.usertracking.proto.TrackingNotificationResponse.prototype.setCreatedat = function(value) {
  return jspb.Message.setProto3IntField(this, 6, value);
};


/**
 * optional string title = 7;
 * @return {string}
 */
proto.project.tracknest.usertracking.proto.TrackingNotificationResponse.prototype.getTitle = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 7, ""));
};


/**
 * @param {string} value
 * @return {!proto.project.tracknest.usertracking.proto.TrackingNotificationResponse} returns this
 */
proto.project.tracknest.usertracking.proto.TrackingNotificationResponse.prototype.setTitle = function(value) {
  return jspb.Message.setProto3StringField(this, 7, value);
};


/**
 * optional string content = 8;
 * @return {string}
 */
proto.project.tracknest.usertracking.proto.TrackingNotificationResponse.prototype.getContent = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 8, ""));
};


/**
 * @param {string} value
 * @return {!proto.project.tracknest.usertracking.proto.TrackingNotificationResponse} returns this
 */
proto.project.tracknest.usertracking.proto.TrackingNotificationResponse.prototype.setContent = function(value) {
  return jspb.Message.setProto3StringField(this, 8, value);
};


/**
 * optional bool seen = 9;
 * @return {boolean}
 */
proto.project.tracknest.usertracking.proto.TrackingNotificationResponse.prototype.getSeen = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 9, false));
};


/**
 * @param {boolean} value
 * @return {!proto.project.tracknest.usertracking.proto.TrackingNotificationResponse} returns this
 */
proto.project.tracknest.usertracking.proto.TrackingNotificationResponse.prototype.setSeen = function(value) {
  return jspb.Message.setProto3BooleanField(this, 9, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.project.tracknest.usertracking.proto.RiskNotificationResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.project.tracknest.usertracking.proto.RiskNotificationResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.project.tracknest.usertracking.proto.RiskNotificationResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.project.tracknest.usertracking.proto.RiskNotificationResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
id: jspb.Message.getFieldWithDefault(msg, 1, ""),
targetid: jspb.Message.getFieldWithDefault(msg, 2, ""),
targetusername: jspb.Message.getFieldWithDefault(msg, 3, ""),
createdat: jspb.Message.getFieldWithDefault(msg, 4, 0),
title: jspb.Message.getFieldWithDefault(msg, 5, ""),
content: jspb.Message.getFieldWithDefault(msg, 6, ""),
seen: jspb.Message.getBooleanFieldWithDefault(msg, 7, false)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.binary.bytesource.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.project.tracknest.usertracking.proto.RiskNotificationResponse}
 */
proto.project.tracknest.usertracking.proto.RiskNotificationResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.project.tracknest.usertracking.proto.RiskNotificationResponse;
  return proto.project.tracknest.usertracking.proto.RiskNotificationResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.project.tracknest.usertracking.proto.RiskNotificationResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.project.tracknest.usertracking.proto.RiskNotificationResponse}
 */
proto.project.tracknest.usertracking.proto.RiskNotificationResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readStringRequireUtf8());
      msg.setId(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readStringRequireUtf8());
      msg.setTargetid(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readStringRequireUtf8());
      msg.setTargetusername(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setCreatedat(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readStringRequireUtf8());
      msg.setTitle(value);
      break;
    case 6:
      var value = /** @type {string} */ (reader.readStringRequireUtf8());
      msg.setContent(value);
      break;
    case 7:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setSeen(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.project.tracknest.usertracking.proto.RiskNotificationResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.project.tracknest.usertracking.proto.RiskNotificationResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.project.tracknest.usertracking.proto.RiskNotificationResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.project.tracknest.usertracking.proto.RiskNotificationResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getTargetid();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getTargetusername();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getCreatedat();
  if (f !== 0) {
    writer.writeUint64(
      4,
      f
    );
  }
  f = message.getTitle();
  if (f.length > 0) {
    writer.writeString(
      5,
      f
    );
  }
  f = message.getContent();
  if (f.length > 0) {
    writer.writeString(
      6,
      f
    );
  }
  f = message.getSeen();
  if (f) {
    writer.writeBool(
      7,
      f
    );
  }
};


/**
 * optional string id = 1;
 * @return {string}
 */
proto.project.tracknest.usertracking.proto.RiskNotificationResponse.prototype.getId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.project.tracknest.usertracking.proto.RiskNotificationResponse} returns this
 */
proto.project.tracknest.usertracking.proto.RiskNotificationResponse.prototype.setId = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string targetId = 2;
 * @return {string}
 */
proto.project.tracknest.usertracking.proto.RiskNotificationResponse.prototype.getTargetid = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.project.tracknest.usertracking.proto.RiskNotificationResponse} returns this
 */
proto.project.tracknest.usertracking.proto.RiskNotificationResponse.prototype.setTargetid = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string targetUsername = 3;
 * @return {string}
 */
proto.project.tracknest.usertracking.proto.RiskNotificationResponse.prototype.getTargetusername = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.project.tracknest.usertracking.proto.RiskNotificationResponse} returns this
 */
proto.project.tracknest.usertracking.proto.RiskNotificationResponse.prototype.setTargetusername = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional uint64 createdAt = 4;
 * @return {number}
 */
proto.project.tracknest.usertracking.proto.RiskNotificationResponse.prototype.getCreatedat = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/**
 * @param {number} value
 * @return {!proto.project.tracknest.usertracking.proto.RiskNotificationResponse} returns this
 */
proto.project.tracknest.usertracking.proto.RiskNotificationResponse.prototype.setCreatedat = function(value) {
  return jspb.Message.setProto3IntField(this, 4, value);
};


/**
 * optional string title = 5;
 * @return {string}
 */
proto.project.tracknest.usertracking.proto.RiskNotificationResponse.prototype.getTitle = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/**
 * @param {string} value
 * @return {!proto.project.tracknest.usertracking.proto.RiskNotificationResponse} returns this
 */
proto.project.tracknest.usertracking.proto.RiskNotificationResponse.prototype.setTitle = function(value) {
  return jspb.Message.setProto3StringField(this, 5, value);
};


/**
 * optional string content = 6;
 * @return {string}
 */
proto.project.tracknest.usertracking.proto.RiskNotificationResponse.prototype.getContent = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 6, ""));
};


/**
 * @param {string} value
 * @return {!proto.project.tracknest.usertracking.proto.RiskNotificationResponse} returns this
 */
proto.project.tracknest.usertracking.proto.RiskNotificationResponse.prototype.setContent = function(value) {
  return jspb.Message.setProto3StringField(this, 6, value);
};


/**
 * optional bool seen = 7;
 * @return {boolean}
 */
proto.project.tracknest.usertracking.proto.RiskNotificationResponse.prototype.getSeen = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 7, false));
};


/**
 * @param {boolean} value
 * @return {!proto.project.tracknest.usertracking.proto.RiskNotificationResponse} returns this
 */
proto.project.tracknest.usertracking.proto.RiskNotificationResponse.prototype.setSeen = function(value) {
  return jspb.Message.setProto3BooleanField(this, 7, value);
};


goog.object.extend(exports, proto.project.tracknest.usertracking.proto);
