/**
 * @fileoverview gRPC-Web generated client stub for project.tracknest.usertracking.proto
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v2.0.2
// 	protoc              v6.33.2
// source: notifier.proto


/* eslint-disable */
// @ts-nocheck


import * as grpcWeb from 'grpc-web';

import * as google_protobuf_empty_pb from 'google-protobuf/google/protobuf/empty_pb'; // proto import: "google/protobuf/empty.proto"
import * as google_protobuf_wrappers_pb from 'google-protobuf/google/protobuf/wrappers_pb'; // proto import: "google/protobuf/wrappers.proto"
import * as notifier_pb from './notifier_pb'; // proto import: "notifier.proto"


export class NotifierControllerClient {
  client_: grpcWeb.AbstractClientBase;
  hostname_: string;
  credentials_: null | { [index: string]: string; };
  options_: null | { [index: string]: any; };

  constructor (hostname: string,
               credentials?: null | { [index: string]: string; },
               options?: null | { [index: string]: any; }) {
    if (!options) options = {};
    if (!credentials) credentials = {};
    options['format'] = 'text';

    this.client_ = new grpcWeb.GrpcWebClientBase(options);
    this.hostname_ = hostname.replace(/\/+$/, '');
    this.credentials_ = credentials;
    this.options_ = options;
  }

  methodDescriptorpostMobileDevice = new grpcWeb.MethodDescriptor(
    '/project.tracknest.usertracking.proto.NotifierController/postMobileDevice',
    grpcWeb.MethodType.UNARY,
    notifier_pb.MobileDeviceRequest,
    google_protobuf_wrappers_pb.StringValue,
    (request: notifier_pb.MobileDeviceRequest) => {
      return request.serializeBinary();
    },
    google_protobuf_wrappers_pb.StringValue.deserializeBinary
  );

  postMobileDevice(
    request: notifier_pb.MobileDeviceRequest,
    metadata?: grpcWeb.Metadata | null): Promise<google_protobuf_wrappers_pb.StringValue>;

  postMobileDevice(
    request: notifier_pb.MobileDeviceRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: google_protobuf_wrappers_pb.StringValue) => void): grpcWeb.ClientReadableStream<google_protobuf_wrappers_pb.StringValue>;

  postMobileDevice(
    request: notifier_pb.MobileDeviceRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: google_protobuf_wrappers_pb.StringValue) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/project.tracknest.usertracking.proto.NotifierController/postMobileDevice',
        request,
        metadata || {},
        this.methodDescriptorpostMobileDevice,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/project.tracknest.usertracking.proto.NotifierController/postMobileDevice',
    request,
    metadata || {},
    this.methodDescriptorpostMobileDevice);
  }

  methodDescriptordeleteMobileDevice = new grpcWeb.MethodDescriptor(
    '/project.tracknest.usertracking.proto.NotifierController/deleteMobileDevice',
    grpcWeb.MethodType.UNARY,
    google_protobuf_wrappers_pb.StringValue,
    google_protobuf_empty_pb.Empty,
    (request: google_protobuf_wrappers_pb.StringValue) => {
      return request.serializeBinary();
    },
    google_protobuf_empty_pb.Empty.deserializeBinary
  );

  deleteMobileDevice(
    request: google_protobuf_wrappers_pb.StringValue,
    metadata?: grpcWeb.Metadata | null): Promise<google_protobuf_empty_pb.Empty>;

  deleteMobileDevice(
    request: google_protobuf_wrappers_pb.StringValue,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: google_protobuf_empty_pb.Empty) => void): grpcWeb.ClientReadableStream<google_protobuf_empty_pb.Empty>;

  deleteMobileDevice(
    request: google_protobuf_wrappers_pb.StringValue,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: google_protobuf_empty_pb.Empty) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/project.tracknest.usertracking.proto.NotifierController/deleteMobileDevice',
        request,
        metadata || {},
        this.methodDescriptordeleteMobileDevice,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/project.tracknest.usertracking.proto.NotifierController/deleteMobileDevice',
    request,
    metadata || {},
    this.methodDescriptordeleteMobileDevice);
  }

  methodDescriptorgetTrackingNotifications = new grpcWeb.MethodDescriptor(
    '/project.tracknest.usertracking.proto.NotifierController/getTrackingNotifications',
    grpcWeb.MethodType.UNARY,
    google_protobuf_empty_pb.Empty,
    notifier_pb.TrackingNotificationResponse,
    (request: google_protobuf_empty_pb.Empty) => {
      return request.serializeBinary();
    },
    notifier_pb.TrackingNotificationResponse.deserializeBinary
  );

  getTrackingNotifications(
    request: google_protobuf_empty_pb.Empty,
    metadata?: grpcWeb.Metadata | null): Promise<notifier_pb.TrackingNotificationResponse>;

  getTrackingNotifications(
    request: google_protobuf_empty_pb.Empty,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: notifier_pb.TrackingNotificationResponse) => void): grpcWeb.ClientReadableStream<notifier_pb.TrackingNotificationResponse>;

  getTrackingNotifications(
    request: google_protobuf_empty_pb.Empty,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: notifier_pb.TrackingNotificationResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/project.tracknest.usertracking.proto.NotifierController/getTrackingNotifications',
        request,
        metadata || {},
        this.methodDescriptorgetTrackingNotifications,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/project.tracknest.usertracking.proto.NotifierController/getTrackingNotifications',
    request,
    metadata || {},
    this.methodDescriptorgetTrackingNotifications);
  }

  methodDescriptorgetRiskNotifications = new grpcWeb.MethodDescriptor(
    '/project.tracknest.usertracking.proto.NotifierController/getRiskNotifications',
    grpcWeb.MethodType.UNARY,
    google_protobuf_empty_pb.Empty,
    notifier_pb.RiskNotificationResponse,
    (request: google_protobuf_empty_pb.Empty) => {
      return request.serializeBinary();
    },
    notifier_pb.RiskNotificationResponse.deserializeBinary
  );

  getRiskNotifications(
    request: google_protobuf_empty_pb.Empty,
    metadata?: grpcWeb.Metadata | null): Promise<notifier_pb.RiskNotificationResponse>;

  getRiskNotifications(
    request: google_protobuf_empty_pb.Empty,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: notifier_pb.RiskNotificationResponse) => void): grpcWeb.ClientReadableStream<notifier_pb.RiskNotificationResponse>;

  getRiskNotifications(
    request: google_protobuf_empty_pb.Empty,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: notifier_pb.RiskNotificationResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/project.tracknest.usertracking.proto.NotifierController/getRiskNotifications',
        request,
        metadata || {},
        this.methodDescriptorgetRiskNotifications,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/project.tracknest.usertracking.proto.NotifierController/getRiskNotifications',
    request,
    metadata || {},
    this.methodDescriptorgetRiskNotifications);
  }

  methodDescriptordeleteTrackingNotification = new grpcWeb.MethodDescriptor(
    '/project.tracknest.usertracking.proto.NotifierController/deleteTrackingNotification',
    grpcWeb.MethodType.UNARY,
    google_protobuf_wrappers_pb.StringValue,
    google_protobuf_empty_pb.Empty,
    (request: google_protobuf_wrappers_pb.StringValue) => {
      return request.serializeBinary();
    },
    google_protobuf_empty_pb.Empty.deserializeBinary
  );

  deleteTrackingNotification(
    request: google_protobuf_wrappers_pb.StringValue,
    metadata?: grpcWeb.Metadata | null): Promise<google_protobuf_empty_pb.Empty>;

  deleteTrackingNotification(
    request: google_protobuf_wrappers_pb.StringValue,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: google_protobuf_empty_pb.Empty) => void): grpcWeb.ClientReadableStream<google_protobuf_empty_pb.Empty>;

  deleteTrackingNotification(
    request: google_protobuf_wrappers_pb.StringValue,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: google_protobuf_empty_pb.Empty) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/project.tracknest.usertracking.proto.NotifierController/deleteTrackingNotification',
        request,
        metadata || {},
        this.methodDescriptordeleteTrackingNotification,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/project.tracknest.usertracking.proto.NotifierController/deleteTrackingNotification',
    request,
    metadata || {},
    this.methodDescriptordeleteTrackingNotification);
  }

  methodDescriptordeleteRiskNotification = new grpcWeb.MethodDescriptor(
    '/project.tracknest.usertracking.proto.NotifierController/deleteRiskNotification',
    grpcWeb.MethodType.UNARY,
    google_protobuf_wrappers_pb.StringValue,
    google_protobuf_empty_pb.Empty,
    (request: google_protobuf_wrappers_pb.StringValue) => {
      return request.serializeBinary();
    },
    google_protobuf_empty_pb.Empty.deserializeBinary
  );

  deleteRiskNotification(
    request: google_protobuf_wrappers_pb.StringValue,
    metadata?: grpcWeb.Metadata | null): Promise<google_protobuf_empty_pb.Empty>;

  deleteRiskNotification(
    request: google_protobuf_wrappers_pb.StringValue,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: google_protobuf_empty_pb.Empty) => void): grpcWeb.ClientReadableStream<google_protobuf_empty_pb.Empty>;

  deleteRiskNotification(
    request: google_protobuf_wrappers_pb.StringValue,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: google_protobuf_empty_pb.Empty) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/project.tracknest.usertracking.proto.NotifierController/deleteRiskNotification',
        request,
        metadata || {},
        this.methodDescriptordeleteRiskNotification,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/project.tracknest.usertracking.proto.NotifierController/deleteRiskNotification',
    request,
    metadata || {},
    this.methodDescriptordeleteRiskNotification);
  }

  methodDescriptordeleteTrackingNotifications = new grpcWeb.MethodDescriptor(
    '/project.tracknest.usertracking.proto.NotifierController/deleteTrackingNotifications',
    grpcWeb.MethodType.UNARY,
    notifier_pb.NotificationIds,
    google_protobuf_empty_pb.Empty,
    (request: notifier_pb.NotificationIds) => {
      return request.serializeBinary();
    },
    google_protobuf_empty_pb.Empty.deserializeBinary
  );

  deleteTrackingNotifications(
    request: notifier_pb.NotificationIds,
    metadata?: grpcWeb.Metadata | null): Promise<google_protobuf_empty_pb.Empty>;

  deleteTrackingNotifications(
    request: notifier_pb.NotificationIds,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: google_protobuf_empty_pb.Empty) => void): grpcWeb.ClientReadableStream<google_protobuf_empty_pb.Empty>;

  deleteTrackingNotifications(
    request: notifier_pb.NotificationIds,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: google_protobuf_empty_pb.Empty) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/project.tracknest.usertracking.proto.NotifierController/deleteTrackingNotifications',
        request,
        metadata || {},
        this.methodDescriptordeleteTrackingNotifications,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/project.tracknest.usertracking.proto.NotifierController/deleteTrackingNotifications',
    request,
    metadata || {},
    this.methodDescriptordeleteTrackingNotifications);
  }

  methodDescriptordeleteRiskNotifications = new grpcWeb.MethodDescriptor(
    '/project.tracknest.usertracking.proto.NotifierController/deleteRiskNotifications',
    grpcWeb.MethodType.UNARY,
    notifier_pb.NotificationIds,
    google_protobuf_empty_pb.Empty,
    (request: notifier_pb.NotificationIds) => {
      return request.serializeBinary();
    },
    google_protobuf_empty_pb.Empty.deserializeBinary
  );

  deleteRiskNotifications(
    request: notifier_pb.NotificationIds,
    metadata?: grpcWeb.Metadata | null): Promise<google_protobuf_empty_pb.Empty>;

  deleteRiskNotifications(
    request: notifier_pb.NotificationIds,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: google_protobuf_empty_pb.Empty) => void): grpcWeb.ClientReadableStream<google_protobuf_empty_pb.Empty>;

  deleteRiskNotifications(
    request: notifier_pb.NotificationIds,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: google_protobuf_empty_pb.Empty) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/project.tracknest.usertracking.proto.NotifierController/deleteRiskNotifications',
        request,
        metadata || {},
        this.methodDescriptordeleteRiskNotifications,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/project.tracknest.usertracking.proto.NotifierController/deleteRiskNotifications',
    request,
    metadata || {},
    this.methodDescriptordeleteRiskNotifications);
  }

  methodDescriptordeleteAllTrackingNotifications = new grpcWeb.MethodDescriptor(
    '/project.tracknest.usertracking.proto.NotifierController/deleteAllTrackingNotifications',
    grpcWeb.MethodType.UNARY,
    google_protobuf_empty_pb.Empty,
    google_protobuf_empty_pb.Empty,
    (request: google_protobuf_empty_pb.Empty) => {
      return request.serializeBinary();
    },
    google_protobuf_empty_pb.Empty.deserializeBinary
  );

  deleteAllTrackingNotifications(
    request: google_protobuf_empty_pb.Empty,
    metadata?: grpcWeb.Metadata | null): Promise<google_protobuf_empty_pb.Empty>;

  deleteAllTrackingNotifications(
    request: google_protobuf_empty_pb.Empty,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: google_protobuf_empty_pb.Empty) => void): grpcWeb.ClientReadableStream<google_protobuf_empty_pb.Empty>;

  deleteAllTrackingNotifications(
    request: google_protobuf_empty_pb.Empty,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: google_protobuf_empty_pb.Empty) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/project.tracknest.usertracking.proto.NotifierController/deleteAllTrackingNotifications',
        request,
        metadata || {},
        this.methodDescriptordeleteAllTrackingNotifications,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/project.tracknest.usertracking.proto.NotifierController/deleteAllTrackingNotifications',
    request,
    metadata || {},
    this.methodDescriptordeleteAllTrackingNotifications);
  }

  methodDescriptordeleteAllRiskNotifications = new grpcWeb.MethodDescriptor(
    '/project.tracknest.usertracking.proto.NotifierController/deleteAllRiskNotifications',
    grpcWeb.MethodType.UNARY,
    google_protobuf_empty_pb.Empty,
    google_protobuf_empty_pb.Empty,
    (request: google_protobuf_empty_pb.Empty) => {
      return request.serializeBinary();
    },
    google_protobuf_empty_pb.Empty.deserializeBinary
  );

  deleteAllRiskNotifications(
    request: google_protobuf_empty_pb.Empty,
    metadata?: grpcWeb.Metadata | null): Promise<google_protobuf_empty_pb.Empty>;

  deleteAllRiskNotifications(
    request: google_protobuf_empty_pb.Empty,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: google_protobuf_empty_pb.Empty) => void): grpcWeb.ClientReadableStream<google_protobuf_empty_pb.Empty>;

  deleteAllRiskNotifications(
    request: google_protobuf_empty_pb.Empty,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: google_protobuf_empty_pb.Empty) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/project.tracknest.usertracking.proto.NotifierController/deleteAllRiskNotifications',
        request,
        metadata || {},
        this.methodDescriptordeleteAllRiskNotifications,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/project.tracknest.usertracking.proto.NotifierController/deleteAllRiskNotifications',
    request,
    metadata || {},
    this.methodDescriptordeleteAllRiskNotifications);
  }

}

