/**
 * @fileoverview gRPC-Web generated client stub for project.tracknest.usertracking.proto
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v2.0.2
// 	protoc              v6.33.2
// source: trackingmanager.proto


/* eslint-disable */
// @ts-nocheck


import * as grpcWeb from 'grpc-web';

import * as google_protobuf_wrappers_pb from 'google-protobuf/google/protobuf/wrappers_pb'; // proto import: "google/protobuf/wrappers.proto"
import * as google_protobuf_empty_pb from 'google-protobuf/google/protobuf/empty_pb'; // proto import: "google/protobuf/empty.proto"
import * as trackingmanager_pb from './trackingmanager_pb'; // proto import: "trackingmanager.proto"


export class TrackingManagerControllerClient {
  client_: grpcWeb.AbstractClientBase;
  hostname_: string;
  credentials_: null | { [index: string]: string; };
  options_: null | { [index: string]: any; };

  constructor (hostname: string,
               credentials?: null | { [index: string]: string; },
               options?: null | { [index: string]: any; }) {
    if (!options) options = {};
    if (!credentials) credentials = {};
    options['format'] = 'text';

    this.client_ = new grpcWeb.GrpcWebClientBase(options);
    this.hostname_ = hostname.replace(/\/+$/, '');
    this.credentials_ = credentials;
    this.options_ = options;
  }

  methodDescriptorpostConnection = new grpcWeb.MethodDescriptor(
    '/project.tracknest.usertracking.proto.TrackingManagerController/postConnection',
    grpcWeb.MethodType.UNARY,
    trackingmanager_pb.ConnectionRequest,
    google_protobuf_empty_pb.Empty,
    (request: trackingmanager_pb.ConnectionRequest) => {
      return request.serializeBinary();
    },
    google_protobuf_empty_pb.Empty.deserializeBinary
  );

  postConnection(
    request: trackingmanager_pb.ConnectionRequest,
    metadata?: grpcWeb.Metadata | null): Promise<google_protobuf_empty_pb.Empty>;

  postConnection(
    request: trackingmanager_pb.ConnectionRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: google_protobuf_empty_pb.Empty) => void): grpcWeb.ClientReadableStream<google_protobuf_empty_pb.Empty>;

  postConnection(
    request: trackingmanager_pb.ConnectionRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: google_protobuf_empty_pb.Empty) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/project.tracknest.usertracking.proto.TrackingManagerController/postConnection',
        request,
        metadata || {},
        this.methodDescriptorpostConnection,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/project.tracknest.usertracking.proto.TrackingManagerController/postConnection',
    request,
    metadata || {},
    this.methodDescriptorpostConnection);
  }

  methodDescriptordeleteTracker = new grpcWeb.MethodDescriptor(
    '/project.tracknest.usertracking.proto.TrackingManagerController/deleteTracker',
    grpcWeb.MethodType.UNARY,
    google_protobuf_wrappers_pb.StringValue,
    google_protobuf_empty_pb.Empty,
    (request: google_protobuf_wrappers_pb.StringValue) => {
      return request.serializeBinary();
    },
    google_protobuf_empty_pb.Empty.deserializeBinary
  );

  deleteTracker(
    request: google_protobuf_wrappers_pb.StringValue,
    metadata?: grpcWeb.Metadata | null): Promise<google_protobuf_empty_pb.Empty>;

  deleteTracker(
    request: google_protobuf_wrappers_pb.StringValue,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: google_protobuf_empty_pb.Empty) => void): grpcWeb.ClientReadableStream<google_protobuf_empty_pb.Empty>;

  deleteTracker(
    request: google_protobuf_wrappers_pb.StringValue,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: google_protobuf_empty_pb.Empty) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/project.tracknest.usertracking.proto.TrackingManagerController/deleteTracker',
        request,
        metadata || {},
        this.methodDescriptordeleteTracker,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/project.tracknest.usertracking.proto.TrackingManagerController/deleteTracker',
    request,
    metadata || {},
    this.methodDescriptordeleteTracker);
  }

  methodDescriptordeleteTarget = new grpcWeb.MethodDescriptor(
    '/project.tracknest.usertracking.proto.TrackingManagerController/deleteTarget',
    grpcWeb.MethodType.UNARY,
    google_protobuf_wrappers_pb.StringValue,
    google_protobuf_empty_pb.Empty,
    (request: google_protobuf_wrappers_pb.StringValue) => {
      return request.serializeBinary();
    },
    google_protobuf_empty_pb.Empty.deserializeBinary
  );

  deleteTarget(
    request: google_protobuf_wrappers_pb.StringValue,
    metadata?: grpcWeb.Metadata | null): Promise<google_protobuf_empty_pb.Empty>;

  deleteTarget(
    request: google_protobuf_wrappers_pb.StringValue,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: google_protobuf_empty_pb.Empty) => void): grpcWeb.ClientReadableStream<google_protobuf_empty_pb.Empty>;

  deleteTarget(
    request: google_protobuf_wrappers_pb.StringValue,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: google_protobuf_empty_pb.Empty) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/project.tracknest.usertracking.proto.TrackingManagerController/deleteTarget',
        request,
        metadata || {},
        this.methodDescriptordeleteTarget,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/project.tracknest.usertracking.proto.TrackingManagerController/deleteTarget',
    request,
    metadata || {},
    this.methodDescriptordeleteTarget);
  }

  methodDescriptorpostTrackingPermission = new grpcWeb.MethodDescriptor(
    '/project.tracknest.usertracking.proto.TrackingManagerController/postTrackingPermission',
    grpcWeb.MethodType.UNARY,
    google_protobuf_empty_pb.Empty,
    trackingmanager_pb.PermissionResponse,
    (request: google_protobuf_empty_pb.Empty) => {
      return request.serializeBinary();
    },
    trackingmanager_pb.PermissionResponse.deserializeBinary
  );

  postTrackingPermission(
    request: google_protobuf_empty_pb.Empty,
    metadata?: grpcWeb.Metadata | null): Promise<trackingmanager_pb.PermissionResponse>;

  postTrackingPermission(
    request: google_protobuf_empty_pb.Empty,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: trackingmanager_pb.PermissionResponse) => void): grpcWeb.ClientReadableStream<trackingmanager_pb.PermissionResponse>;

  postTrackingPermission(
    request: google_protobuf_empty_pb.Empty,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: trackingmanager_pb.PermissionResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/project.tracknest.usertracking.proto.TrackingManagerController/postTrackingPermission',
        request,
        metadata || {},
        this.methodDescriptorpostTrackingPermission,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/project.tracknest.usertracking.proto.TrackingManagerController/postTrackingPermission',
    request,
    metadata || {},
    this.methodDescriptorpostTrackingPermission);
  }

  methodDescriptordeleteTrackingPermission = new grpcWeb.MethodDescriptor(
    '/project.tracknest.usertracking.proto.TrackingManagerController/deleteTrackingPermission',
    grpcWeb.MethodType.UNARY,
    google_protobuf_wrappers_pb.StringValue,
    google_protobuf_empty_pb.Empty,
    (request: google_protobuf_wrappers_pb.StringValue) => {
      return request.serializeBinary();
    },
    google_protobuf_empty_pb.Empty.deserializeBinary
  );

  deleteTrackingPermission(
    request: google_protobuf_wrappers_pb.StringValue,
    metadata?: grpcWeb.Metadata | null): Promise<google_protobuf_empty_pb.Empty>;

  deleteTrackingPermission(
    request: google_protobuf_wrappers_pb.StringValue,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: google_protobuf_empty_pb.Empty) => void): grpcWeb.ClientReadableStream<google_protobuf_empty_pb.Empty>;

  deleteTrackingPermission(
    request: google_protobuf_wrappers_pb.StringValue,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: google_protobuf_empty_pb.Empty) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/project.tracknest.usertracking.proto.TrackingManagerController/deleteTrackingPermission',
        request,
        metadata || {},
        this.methodDescriptordeleteTrackingPermission,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/project.tracknest.usertracking.proto.TrackingManagerController/deleteTrackingPermission',
    request,
    metadata || {},
    this.methodDescriptordeleteTrackingPermission);
  }

  methodDescriptorgetUserTargets = new grpcWeb.MethodDescriptor(
    '/project.tracknest.usertracking.proto.TrackingManagerController/getUserTargets',
    grpcWeb.MethodType.SERVER_STREAMING,
    google_protobuf_empty_pb.Empty,
    trackingmanager_pb.TargetResponse,
    (request: google_protobuf_empty_pb.Empty) => {
      return request.serializeBinary();
    },
    trackingmanager_pb.TargetResponse.deserializeBinary
  );

  getUserTargets(
    request: google_protobuf_empty_pb.Empty,
    metadata?: grpcWeb.Metadata): grpcWeb.ClientReadableStream<trackingmanager_pb.TargetResponse> {
    return this.client_.serverStreaming(
      this.hostname_ +
        '/project.tracknest.usertracking.proto.TrackingManagerController/getUserTargets',
      request,
      metadata || {},
      this.methodDescriptorgetUserTargets);
  }

  methodDescriptorgetUserTrackers = new grpcWeb.MethodDescriptor(
    '/project.tracknest.usertracking.proto.TrackingManagerController/getUserTrackers',
    grpcWeb.MethodType.SERVER_STREAMING,
    google_protobuf_empty_pb.Empty,
    trackingmanager_pb.TrackerResponse,
    (request: google_protobuf_empty_pb.Empty) => {
      return request.serializeBinary();
    },
    trackingmanager_pb.TrackerResponse.deserializeBinary
  );

  getUserTrackers(
    request: google_protobuf_empty_pb.Empty,
    metadata?: grpcWeb.Metadata): grpcWeb.ClientReadableStream<trackingmanager_pb.TrackerResponse> {
    return this.client_.serverStreaming(
      this.hostname_ +
        '/project.tracknest.usertracking.proto.TrackingManagerController/getUserTrackers',
      request,
      metadata || {},
      this.methodDescriptorgetUserTrackers);
  }

  methodDescriptorputTrackingStatus = new grpcWeb.MethodDescriptor(
    '/project.tracknest.usertracking.proto.TrackingManagerController/putTrackingStatus',
    grpcWeb.MethodType.UNARY,
    google_protobuf_wrappers_pb.BoolValue,
    google_protobuf_empty_pb.Empty,
    (request: google_protobuf_wrappers_pb.BoolValue) => {
      return request.serializeBinary();
    },
    google_protobuf_empty_pb.Empty.deserializeBinary
  );

  putTrackingStatus(
    request: google_protobuf_wrappers_pb.BoolValue,
    metadata?: grpcWeb.Metadata | null): Promise<google_protobuf_empty_pb.Empty>;

  putTrackingStatus(
    request: google_protobuf_wrappers_pb.BoolValue,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: google_protobuf_empty_pb.Empty) => void): grpcWeb.ClientReadableStream<google_protobuf_empty_pb.Empty>;

  putTrackingStatus(
    request: google_protobuf_wrappers_pb.BoolValue,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: google_protobuf_empty_pb.Empty) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/project.tracknest.usertracking.proto.TrackingManagerController/putTrackingStatus',
        request,
        metadata || {},
        this.methodDescriptorputTrackingStatus,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/project.tracknest.usertracking.proto.TrackingManagerController/putTrackingStatus',
    request,
    metadata || {},
    this.methodDescriptorputTrackingStatus);
  }

}

