// source: tracker.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global =
    (typeof globalThis !== 'undefined' && globalThis) ||
    (typeof window !== 'undefined' && window) ||
    (typeof global !== 'undefined' && global) ||
    (typeof self !== 'undefined' && self) ||
    (function () { return this; }).call(null) ||
    Function('return this')();

var google_rpc_status_pb = require('./google/rpc/status_pb.js');
goog.object.extend(proto, google_rpc_status_pb);
goog.exportSymbol('proto.project.tracknest.usertracking.proto.v1.FamilyMemberLocation', null, global);
goog.exportSymbol('proto.project.tracknest.usertracking.proto.v1.ListFamilyMemberLocationHistoryRequest', null, global);
goog.exportSymbol('proto.project.tracknest.usertracking.proto.v1.ListFamilyMemberLocationHistoryResponse', null, global);
goog.exportSymbol('proto.project.tracknest.usertracking.proto.v1.StreamFamilyMemberLocationsRequest', null, global);
goog.exportSymbol('proto.project.tracknest.usertracking.proto.v1.UpdateUserLocationRequest', null, global);
goog.exportSymbol('proto.project.tracknest.usertracking.proto.v1.UpdateUserLocationResponse', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.project.tracknest.usertracking.proto.v1.StreamFamilyMemberLocationsRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.project.tracknest.usertracking.proto.v1.StreamFamilyMemberLocationsRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.project.tracknest.usertracking.proto.v1.StreamFamilyMemberLocationsRequest.displayName = 'proto.project.tracknest.usertracking.proto.v1.StreamFamilyMemberLocationsRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.project.tracknest.usertracking.proto.v1.FamilyMemberLocation = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.project.tracknest.usertracking.proto.v1.FamilyMemberLocation, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.project.tracknest.usertracking.proto.v1.FamilyMemberLocation.displayName = 'proto.project.tracknest.usertracking.proto.v1.FamilyMemberLocation';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.project.tracknest.usertracking.proto.v1.ListFamilyMemberLocationHistoryRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.project.tracknest.usertracking.proto.v1.ListFamilyMemberLocationHistoryRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.project.tracknest.usertracking.proto.v1.ListFamilyMemberLocationHistoryRequest.displayName = 'proto.project.tracknest.usertracking.proto.v1.ListFamilyMemberLocationHistoryRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.project.tracknest.usertracking.proto.v1.ListFamilyMemberLocationHistoryResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.project.tracknest.usertracking.proto.v1.ListFamilyMemberLocationHistoryResponse.repeatedFields_, null);
};
goog.inherits(proto.project.tracknest.usertracking.proto.v1.ListFamilyMemberLocationHistoryResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.project.tracknest.usertracking.proto.v1.ListFamilyMemberLocationHistoryResponse.displayName = 'proto.project.tracknest.usertracking.proto.v1.ListFamilyMemberLocationHistoryResponse';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.project.tracknest.usertracking.proto.v1.UpdateUserLocationRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.project.tracknest.usertracking.proto.v1.UpdateUserLocationRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.project.tracknest.usertracking.proto.v1.UpdateUserLocationRequest.displayName = 'proto.project.tracknest.usertracking.proto.v1.UpdateUserLocationRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.project.tracknest.usertracking.proto.v1.UpdateUserLocationResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.project.tracknest.usertracking.proto.v1.UpdateUserLocationResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.project.tracknest.usertracking.proto.v1.UpdateUserLocationResponse.displayName = 'proto.project.tracknest.usertracking.proto.v1.UpdateUserLocationResponse';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.project.tracknest.usertracking.proto.v1.StreamFamilyMemberLocationsRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.project.tracknest.usertracking.proto.v1.StreamFamilyMemberLocationsRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.project.tracknest.usertracking.proto.v1.StreamFamilyMemberLocationsRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.project.tracknest.usertracking.proto.v1.StreamFamilyMemberLocationsRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
familyCircleId: jspb.Message.getFieldWithDefault(msg, 1, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.project.tracknest.usertracking.proto.v1.StreamFamilyMemberLocationsRequest}
 */
proto.project.tracknest.usertracking.proto.v1.StreamFamilyMemberLocationsRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.project.tracknest.usertracking.proto.v1.StreamFamilyMemberLocationsRequest;
  return proto.project.tracknest.usertracking.proto.v1.StreamFamilyMemberLocationsRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.project.tracknest.usertracking.proto.v1.StreamFamilyMemberLocationsRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.project.tracknest.usertracking.proto.v1.StreamFamilyMemberLocationsRequest}
 */
proto.project.tracknest.usertracking.proto.v1.StreamFamilyMemberLocationsRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setFamilyCircleId(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.project.tracknest.usertracking.proto.v1.StreamFamilyMemberLocationsRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.project.tracknest.usertracking.proto.v1.StreamFamilyMemberLocationsRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.project.tracknest.usertracking.proto.v1.StreamFamilyMemberLocationsRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.project.tracknest.usertracking.proto.v1.StreamFamilyMemberLocationsRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getFamilyCircleId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
};


/**
 * optional string family_circle_id = 1;
 * @return {string}
 */
proto.project.tracknest.usertracking.proto.v1.StreamFamilyMemberLocationsRequest.prototype.getFamilyCircleId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.project.tracknest.usertracking.proto.v1.StreamFamilyMemberLocationsRequest} returns this
 */
proto.project.tracknest.usertracking.proto.v1.StreamFamilyMemberLocationsRequest.prototype.setFamilyCircleId = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.project.tracknest.usertracking.proto.v1.FamilyMemberLocation.prototype.toObject = function(opt_includeInstance) {
  return proto.project.tracknest.usertracking.proto.v1.FamilyMemberLocation.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.project.tracknest.usertracking.proto.v1.FamilyMemberLocation} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.project.tracknest.usertracking.proto.v1.FamilyMemberLocation.toObject = function(includeInstance, msg) {
  var f, obj = {
memberId: jspb.Message.getFieldWithDefault(msg, 1, ""),
memberUsername: jspb.Message.getFieldWithDefault(msg, 2, ""),
memberAvatarUrl: (f = jspb.Message.getField(msg, 3)) == null ? undefined : f,
latitudeDeg: jspb.Message.getFloatingPointFieldWithDefault(msg, 4, 0.0),
longitudeDeg: jspb.Message.getFloatingPointFieldWithDefault(msg, 5, 0.0),
accuracyMeter: jspb.Message.getFloatingPointFieldWithDefault(msg, 6, 0.0),
velocityMps: jspb.Message.getFloatingPointFieldWithDefault(msg, 7, 0.0),
timestampMs: jspb.Message.getFieldWithDefault(msg, 8, 0),
online: jspb.Message.getBooleanFieldWithDefault(msg, 9, false),
lastActiveMs: jspb.Message.getFieldWithDefault(msg, 10, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.project.tracknest.usertracking.proto.v1.FamilyMemberLocation}
 */
proto.project.tracknest.usertracking.proto.v1.FamilyMemberLocation.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.project.tracknest.usertracking.proto.v1.FamilyMemberLocation;
  return proto.project.tracknest.usertracking.proto.v1.FamilyMemberLocation.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.project.tracknest.usertracking.proto.v1.FamilyMemberLocation} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.project.tracknest.usertracking.proto.v1.FamilyMemberLocation}
 */
proto.project.tracknest.usertracking.proto.v1.FamilyMemberLocation.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setMemberId(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setMemberUsername(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setMemberAvatarUrl(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setLatitudeDeg(value);
      break;
    case 5:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setLongitudeDeg(value);
      break;
    case 6:
      var value = /** @type {number} */ (reader.readFloat());
      msg.setAccuracyMeter(value);
      break;
    case 7:
      var value = /** @type {number} */ (reader.readFloat());
      msg.setVelocityMps(value);
      break;
    case 8:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setTimestampMs(value);
      break;
    case 9:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setOnline(value);
      break;
    case 10:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setLastActiveMs(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.project.tracknest.usertracking.proto.v1.FamilyMemberLocation.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.project.tracknest.usertracking.proto.v1.FamilyMemberLocation.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.project.tracknest.usertracking.proto.v1.FamilyMemberLocation} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.project.tracknest.usertracking.proto.v1.FamilyMemberLocation.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getMemberId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getMemberUsername();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = /** @type {string} */ (jspb.Message.getField(message, 3));
  if (f != null) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getLatitudeDeg();
  if (f !== 0.0) {
    writer.writeDouble(
      4,
      f
    );
  }
  f = message.getLongitudeDeg();
  if (f !== 0.0) {
    writer.writeDouble(
      5,
      f
    );
  }
  f = message.getAccuracyMeter();
  if (f !== 0.0) {
    writer.writeFloat(
      6,
      f
    );
  }
  f = message.getVelocityMps();
  if (f !== 0.0) {
    writer.writeFloat(
      7,
      f
    );
  }
  f = message.getTimestampMs();
  if (f !== 0) {
    writer.writeUint64(
      8,
      f
    );
  }
  f = message.getOnline();
  if (f) {
    writer.writeBool(
      9,
      f
    );
  }
  f = message.getLastActiveMs();
  if (f !== 0) {
    writer.writeUint64(
      10,
      f
    );
  }
};


/**
 * optional string member_id = 1;
 * @return {string}
 */
proto.project.tracknest.usertracking.proto.v1.FamilyMemberLocation.prototype.getMemberId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.project.tracknest.usertracking.proto.v1.FamilyMemberLocation} returns this
 */
proto.project.tracknest.usertracking.proto.v1.FamilyMemberLocation.prototype.setMemberId = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string member_username = 2;
 * @return {string}
 */
proto.project.tracknest.usertracking.proto.v1.FamilyMemberLocation.prototype.getMemberUsername = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.project.tracknest.usertracking.proto.v1.FamilyMemberLocation} returns this
 */
proto.project.tracknest.usertracking.proto.v1.FamilyMemberLocation.prototype.setMemberUsername = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string member_avatar_url = 3;
 * @return {string}
 */
proto.project.tracknest.usertracking.proto.v1.FamilyMemberLocation.prototype.getMemberAvatarUrl = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.project.tracknest.usertracking.proto.v1.FamilyMemberLocation} returns this
 */
proto.project.tracknest.usertracking.proto.v1.FamilyMemberLocation.prototype.setMemberAvatarUrl = function(value) {
  return jspb.Message.setField(this, 3, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.project.tracknest.usertracking.proto.v1.FamilyMemberLocation} returns this
 */
proto.project.tracknest.usertracking.proto.v1.FamilyMemberLocation.prototype.clearMemberAvatarUrl = function() {
  return jspb.Message.setField(this, 3, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.project.tracknest.usertracking.proto.v1.FamilyMemberLocation.prototype.hasMemberAvatarUrl = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional double latitude_deg = 4;
 * @return {number}
 */
proto.project.tracknest.usertracking.proto.v1.FamilyMemberLocation.prototype.getLatitudeDeg = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 4, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.project.tracknest.usertracking.proto.v1.FamilyMemberLocation} returns this
 */
proto.project.tracknest.usertracking.proto.v1.FamilyMemberLocation.prototype.setLatitudeDeg = function(value) {
  return jspb.Message.setProto3FloatField(this, 4, value);
};


/**
 * optional double longitude_deg = 5;
 * @return {number}
 */
proto.project.tracknest.usertracking.proto.v1.FamilyMemberLocation.prototype.getLongitudeDeg = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 5, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.project.tracknest.usertracking.proto.v1.FamilyMemberLocation} returns this
 */
proto.project.tracknest.usertracking.proto.v1.FamilyMemberLocation.prototype.setLongitudeDeg = function(value) {
  return jspb.Message.setProto3FloatField(this, 5, value);
};


/**
 * optional float accuracy_meter = 6;
 * @return {number}
 */
proto.project.tracknest.usertracking.proto.v1.FamilyMemberLocation.prototype.getAccuracyMeter = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 6, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.project.tracknest.usertracking.proto.v1.FamilyMemberLocation} returns this
 */
proto.project.tracknest.usertracking.proto.v1.FamilyMemberLocation.prototype.setAccuracyMeter = function(value) {
  return jspb.Message.setProto3FloatField(this, 6, value);
};


/**
 * optional float velocity_mps = 7;
 * @return {number}
 */
proto.project.tracknest.usertracking.proto.v1.FamilyMemberLocation.prototype.getVelocityMps = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 7, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.project.tracknest.usertracking.proto.v1.FamilyMemberLocation} returns this
 */
proto.project.tracknest.usertracking.proto.v1.FamilyMemberLocation.prototype.setVelocityMps = function(value) {
  return jspb.Message.setProto3FloatField(this, 7, value);
};


/**
 * optional uint64 timestamp_ms = 8;
 * @return {number}
 */
proto.project.tracknest.usertracking.proto.v1.FamilyMemberLocation.prototype.getTimestampMs = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 8, 0));
};


/**
 * @param {number} value
 * @return {!proto.project.tracknest.usertracking.proto.v1.FamilyMemberLocation} returns this
 */
proto.project.tracknest.usertracking.proto.v1.FamilyMemberLocation.prototype.setTimestampMs = function(value) {
  return jspb.Message.setProto3IntField(this, 8, value);
};


/**
 * optional bool online = 9;
 * @return {boolean}
 */
proto.project.tracknest.usertracking.proto.v1.FamilyMemberLocation.prototype.getOnline = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 9, false));
};


/**
 * @param {boolean} value
 * @return {!proto.project.tracknest.usertracking.proto.v1.FamilyMemberLocation} returns this
 */
proto.project.tracknest.usertracking.proto.v1.FamilyMemberLocation.prototype.setOnline = function(value) {
  return jspb.Message.setProto3BooleanField(this, 9, value);
};


/**
 * optional uint64 last_active_ms = 10;
 * @return {number}
 */
proto.project.tracknest.usertracking.proto.v1.FamilyMemberLocation.prototype.getLastActiveMs = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 10, 0));
};


/**
 * @param {number} value
 * @return {!proto.project.tracknest.usertracking.proto.v1.FamilyMemberLocation} returns this
 */
proto.project.tracknest.usertracking.proto.v1.FamilyMemberLocation.prototype.setLastActiveMs = function(value) {
  return jspb.Message.setProto3IntField(this, 10, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.project.tracknest.usertracking.proto.v1.ListFamilyMemberLocationHistoryRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.project.tracknest.usertracking.proto.v1.ListFamilyMemberLocationHistoryRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.project.tracknest.usertracking.proto.v1.ListFamilyMemberLocationHistoryRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.project.tracknest.usertracking.proto.v1.ListFamilyMemberLocationHistoryRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
familyCircleId: jspb.Message.getFieldWithDefault(msg, 1, ""),
memberId: jspb.Message.getFieldWithDefault(msg, 2, ""),
memberUsername: jspb.Message.getFieldWithDefault(msg, 3, ""),
memberAvatarUrl: (f = jspb.Message.getField(msg, 4)) == null ? undefined : f,
centerLatitudeDeg: (f = jspb.Message.getOptionalFloatingPointField(msg, 5)) == null ? undefined : f,
centerLongitudeDeg: (f = jspb.Message.getOptionalFloatingPointField(msg, 6)) == null ? undefined : f,
radiusMeter: (f = jspb.Message.getOptionalFloatingPointField(msg, 7)) == null ? undefined : f
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.project.tracknest.usertracking.proto.v1.ListFamilyMemberLocationHistoryRequest}
 */
proto.project.tracknest.usertracking.proto.v1.ListFamilyMemberLocationHistoryRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.project.tracknest.usertracking.proto.v1.ListFamilyMemberLocationHistoryRequest;
  return proto.project.tracknest.usertracking.proto.v1.ListFamilyMemberLocationHistoryRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.project.tracknest.usertracking.proto.v1.ListFamilyMemberLocationHistoryRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.project.tracknest.usertracking.proto.v1.ListFamilyMemberLocationHistoryRequest}
 */
proto.project.tracknest.usertracking.proto.v1.ListFamilyMemberLocationHistoryRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setFamilyCircleId(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setMemberId(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setMemberUsername(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setMemberAvatarUrl(value);
      break;
    case 5:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setCenterLatitudeDeg(value);
      break;
    case 6:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setCenterLongitudeDeg(value);
      break;
    case 7:
      var value = /** @type {number} */ (reader.readFloat());
      msg.setRadiusMeter(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.project.tracknest.usertracking.proto.v1.ListFamilyMemberLocationHistoryRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.project.tracknest.usertracking.proto.v1.ListFamilyMemberLocationHistoryRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.project.tracknest.usertracking.proto.v1.ListFamilyMemberLocationHistoryRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.project.tracknest.usertracking.proto.v1.ListFamilyMemberLocationHistoryRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getFamilyCircleId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getMemberId();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getMemberUsername();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = /** @type {string} */ (jspb.Message.getField(message, 4));
  if (f != null) {
    writer.writeString(
      4,
      f
    );
  }
  f = /** @type {number} */ (jspb.Message.getField(message, 5));
  if (f != null) {
    writer.writeDouble(
      5,
      f
    );
  }
  f = /** @type {number} */ (jspb.Message.getField(message, 6));
  if (f != null) {
    writer.writeDouble(
      6,
      f
    );
  }
  f = /** @type {number} */ (jspb.Message.getField(message, 7));
  if (f != null) {
    writer.writeFloat(
      7,
      f
    );
  }
};


/**
 * optional string family_circle_id = 1;
 * @return {string}
 */
proto.project.tracknest.usertracking.proto.v1.ListFamilyMemberLocationHistoryRequest.prototype.getFamilyCircleId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.project.tracknest.usertracking.proto.v1.ListFamilyMemberLocationHistoryRequest} returns this
 */
proto.project.tracknest.usertracking.proto.v1.ListFamilyMemberLocationHistoryRequest.prototype.setFamilyCircleId = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string member_id = 2;
 * @return {string}
 */
proto.project.tracknest.usertracking.proto.v1.ListFamilyMemberLocationHistoryRequest.prototype.getMemberId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.project.tracknest.usertracking.proto.v1.ListFamilyMemberLocationHistoryRequest} returns this
 */
proto.project.tracknest.usertracking.proto.v1.ListFamilyMemberLocationHistoryRequest.prototype.setMemberId = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string member_username = 3;
 * @return {string}
 */
proto.project.tracknest.usertracking.proto.v1.ListFamilyMemberLocationHistoryRequest.prototype.getMemberUsername = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.project.tracknest.usertracking.proto.v1.ListFamilyMemberLocationHistoryRequest} returns this
 */
proto.project.tracknest.usertracking.proto.v1.ListFamilyMemberLocationHistoryRequest.prototype.setMemberUsername = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional string member_avatar_url = 4;
 * @return {string}
 */
proto.project.tracknest.usertracking.proto.v1.ListFamilyMemberLocationHistoryRequest.prototype.getMemberAvatarUrl = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * @param {string} value
 * @return {!proto.project.tracknest.usertracking.proto.v1.ListFamilyMemberLocationHistoryRequest} returns this
 */
proto.project.tracknest.usertracking.proto.v1.ListFamilyMemberLocationHistoryRequest.prototype.setMemberAvatarUrl = function(value) {
  return jspb.Message.setField(this, 4, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.project.tracknest.usertracking.proto.v1.ListFamilyMemberLocationHistoryRequest} returns this
 */
proto.project.tracknest.usertracking.proto.v1.ListFamilyMemberLocationHistoryRequest.prototype.clearMemberAvatarUrl = function() {
  return jspb.Message.setField(this, 4, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.project.tracknest.usertracking.proto.v1.ListFamilyMemberLocationHistoryRequest.prototype.hasMemberAvatarUrl = function() {
  return jspb.Message.getField(this, 4) != null;
};


/**
 * optional double center_latitude_deg = 5;
 * @return {number}
 */
proto.project.tracknest.usertracking.proto.v1.ListFamilyMemberLocationHistoryRequest.prototype.getCenterLatitudeDeg = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 5, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.project.tracknest.usertracking.proto.v1.ListFamilyMemberLocationHistoryRequest} returns this
 */
proto.project.tracknest.usertracking.proto.v1.ListFamilyMemberLocationHistoryRequest.prototype.setCenterLatitudeDeg = function(value) {
  return jspb.Message.setField(this, 5, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.project.tracknest.usertracking.proto.v1.ListFamilyMemberLocationHistoryRequest} returns this
 */
proto.project.tracknest.usertracking.proto.v1.ListFamilyMemberLocationHistoryRequest.prototype.clearCenterLatitudeDeg = function() {
  return jspb.Message.setField(this, 5, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.project.tracknest.usertracking.proto.v1.ListFamilyMemberLocationHistoryRequest.prototype.hasCenterLatitudeDeg = function() {
  return jspb.Message.getField(this, 5) != null;
};


/**
 * optional double center_longitude_deg = 6;
 * @return {number}
 */
proto.project.tracknest.usertracking.proto.v1.ListFamilyMemberLocationHistoryRequest.prototype.getCenterLongitudeDeg = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 6, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.project.tracknest.usertracking.proto.v1.ListFamilyMemberLocationHistoryRequest} returns this
 */
proto.project.tracknest.usertracking.proto.v1.ListFamilyMemberLocationHistoryRequest.prototype.setCenterLongitudeDeg = function(value) {
  return jspb.Message.setField(this, 6, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.project.tracknest.usertracking.proto.v1.ListFamilyMemberLocationHistoryRequest} returns this
 */
proto.project.tracknest.usertracking.proto.v1.ListFamilyMemberLocationHistoryRequest.prototype.clearCenterLongitudeDeg = function() {
  return jspb.Message.setField(this, 6, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.project.tracknest.usertracking.proto.v1.ListFamilyMemberLocationHistoryRequest.prototype.hasCenterLongitudeDeg = function() {
  return jspb.Message.getField(this, 6) != null;
};


/**
 * optional float radius_meter = 7;
 * @return {number}
 */
proto.project.tracknest.usertracking.proto.v1.ListFamilyMemberLocationHistoryRequest.prototype.getRadiusMeter = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 7, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.project.tracknest.usertracking.proto.v1.ListFamilyMemberLocationHistoryRequest} returns this
 */
proto.project.tracknest.usertracking.proto.v1.ListFamilyMemberLocationHistoryRequest.prototype.setRadiusMeter = function(value) {
  return jspb.Message.setField(this, 7, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.project.tracknest.usertracking.proto.v1.ListFamilyMemberLocationHistoryRequest} returns this
 */
proto.project.tracknest.usertracking.proto.v1.ListFamilyMemberLocationHistoryRequest.prototype.clearRadiusMeter = function() {
  return jspb.Message.setField(this, 7, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.project.tracknest.usertracking.proto.v1.ListFamilyMemberLocationHistoryRequest.prototype.hasRadiusMeter = function() {
  return jspb.Message.getField(this, 7) != null;
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.project.tracknest.usertracking.proto.v1.ListFamilyMemberLocationHistoryResponse.repeatedFields_ = [2];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.project.tracknest.usertracking.proto.v1.ListFamilyMemberLocationHistoryResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.project.tracknest.usertracking.proto.v1.ListFamilyMemberLocationHistoryResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.project.tracknest.usertracking.proto.v1.ListFamilyMemberLocationHistoryResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.project.tracknest.usertracking.proto.v1.ListFamilyMemberLocationHistoryResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
status: (f = msg.getStatus()) && google_rpc_status_pb.Status.toObject(includeInstance, f),
locationsList: jspb.Message.toObjectList(msg.getLocationsList(),
    proto.project.tracknest.usertracking.proto.v1.FamilyMemberLocation.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.project.tracknest.usertracking.proto.v1.ListFamilyMemberLocationHistoryResponse}
 */
proto.project.tracknest.usertracking.proto.v1.ListFamilyMemberLocationHistoryResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.project.tracknest.usertracking.proto.v1.ListFamilyMemberLocationHistoryResponse;
  return proto.project.tracknest.usertracking.proto.v1.ListFamilyMemberLocationHistoryResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.project.tracknest.usertracking.proto.v1.ListFamilyMemberLocationHistoryResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.project.tracknest.usertracking.proto.v1.ListFamilyMemberLocationHistoryResponse}
 */
proto.project.tracknest.usertracking.proto.v1.ListFamilyMemberLocationHistoryResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new google_rpc_status_pb.Status;
      reader.readMessage(value,google_rpc_status_pb.Status.deserializeBinaryFromReader);
      msg.setStatus(value);
      break;
    case 2:
      var value = new proto.project.tracknest.usertracking.proto.v1.FamilyMemberLocation;
      reader.readMessage(value,proto.project.tracknest.usertracking.proto.v1.FamilyMemberLocation.deserializeBinaryFromReader);
      msg.addLocations(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.project.tracknest.usertracking.proto.v1.ListFamilyMemberLocationHistoryResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.project.tracknest.usertracking.proto.v1.ListFamilyMemberLocationHistoryResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.project.tracknest.usertracking.proto.v1.ListFamilyMemberLocationHistoryResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.project.tracknest.usertracking.proto.v1.ListFamilyMemberLocationHistoryResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getStatus();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      google_rpc_status_pb.Status.serializeBinaryToWriter
    );
  }
  f = message.getLocationsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      2,
      f,
      proto.project.tracknest.usertracking.proto.v1.FamilyMemberLocation.serializeBinaryToWriter
    );
  }
};


/**
 * optional google.rpc.Status status = 1;
 * @return {?proto.google.rpc.Status}
 */
proto.project.tracknest.usertracking.proto.v1.ListFamilyMemberLocationHistoryResponse.prototype.getStatus = function() {
  return /** @type{?proto.google.rpc.Status} */ (
    jspb.Message.getWrapperField(this, google_rpc_status_pb.Status, 1));
};


/**
 * @param {?proto.google.rpc.Status|undefined} value
 * @return {!proto.project.tracknest.usertracking.proto.v1.ListFamilyMemberLocationHistoryResponse} returns this
*/
proto.project.tracknest.usertracking.proto.v1.ListFamilyMemberLocationHistoryResponse.prototype.setStatus = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.project.tracknest.usertracking.proto.v1.ListFamilyMemberLocationHistoryResponse} returns this
 */
proto.project.tracknest.usertracking.proto.v1.ListFamilyMemberLocationHistoryResponse.prototype.clearStatus = function() {
  return this.setStatus(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.project.tracknest.usertracking.proto.v1.ListFamilyMemberLocationHistoryResponse.prototype.hasStatus = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * repeated FamilyMemberLocation locations = 2;
 * @return {!Array<!proto.project.tracknest.usertracking.proto.v1.FamilyMemberLocation>}
 */
proto.project.tracknest.usertracking.proto.v1.ListFamilyMemberLocationHistoryResponse.prototype.getLocationsList = function() {
  return /** @type{!Array<!proto.project.tracknest.usertracking.proto.v1.FamilyMemberLocation>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.project.tracknest.usertracking.proto.v1.FamilyMemberLocation, 2));
};


/**
 * @param {!Array<!proto.project.tracknest.usertracking.proto.v1.FamilyMemberLocation>} value
 * @return {!proto.project.tracknest.usertracking.proto.v1.ListFamilyMemberLocationHistoryResponse} returns this
*/
proto.project.tracknest.usertracking.proto.v1.ListFamilyMemberLocationHistoryResponse.prototype.setLocationsList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 2, value);
};


/**
 * @param {!proto.project.tracknest.usertracking.proto.v1.FamilyMemberLocation=} opt_value
 * @param {number=} opt_index
 * @return {!proto.project.tracknest.usertracking.proto.v1.FamilyMemberLocation}
 */
proto.project.tracknest.usertracking.proto.v1.ListFamilyMemberLocationHistoryResponse.prototype.addLocations = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 2, opt_value, proto.project.tracknest.usertracking.proto.v1.FamilyMemberLocation, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.project.tracknest.usertracking.proto.v1.ListFamilyMemberLocationHistoryResponse} returns this
 */
proto.project.tracknest.usertracking.proto.v1.ListFamilyMemberLocationHistoryResponse.prototype.clearLocationsList = function() {
  return this.setLocationsList([]);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.project.tracknest.usertracking.proto.v1.UpdateUserLocationRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.project.tracknest.usertracking.proto.v1.UpdateUserLocationRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.project.tracknest.usertracking.proto.v1.UpdateUserLocationRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.project.tracknest.usertracking.proto.v1.UpdateUserLocationRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
latitudeDeg: jspb.Message.getFloatingPointFieldWithDefault(msg, 1, 0.0),
longitudeDeg: jspb.Message.getFloatingPointFieldWithDefault(msg, 2, 0.0),
accuracyMeter: jspb.Message.getFloatingPointFieldWithDefault(msg, 3, 0.0),
velocityMps: jspb.Message.getFloatingPointFieldWithDefault(msg, 4, 0.0),
timestampMs: jspb.Message.getFieldWithDefault(msg, 5, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.project.tracknest.usertracking.proto.v1.UpdateUserLocationRequest}
 */
proto.project.tracknest.usertracking.proto.v1.UpdateUserLocationRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.project.tracknest.usertracking.proto.v1.UpdateUserLocationRequest;
  return proto.project.tracknest.usertracking.proto.v1.UpdateUserLocationRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.project.tracknest.usertracking.proto.v1.UpdateUserLocationRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.project.tracknest.usertracking.proto.v1.UpdateUserLocationRequest}
 */
proto.project.tracknest.usertracking.proto.v1.UpdateUserLocationRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setLatitudeDeg(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setLongitudeDeg(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readFloat());
      msg.setAccuracyMeter(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readFloat());
      msg.setVelocityMps(value);
      break;
    case 5:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setTimestampMs(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.project.tracknest.usertracking.proto.v1.UpdateUserLocationRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.project.tracknest.usertracking.proto.v1.UpdateUserLocationRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.project.tracknest.usertracking.proto.v1.UpdateUserLocationRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.project.tracknest.usertracking.proto.v1.UpdateUserLocationRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getLatitudeDeg();
  if (f !== 0.0) {
    writer.writeDouble(
      1,
      f
    );
  }
  f = message.getLongitudeDeg();
  if (f !== 0.0) {
    writer.writeDouble(
      2,
      f
    );
  }
  f = message.getAccuracyMeter();
  if (f !== 0.0) {
    writer.writeFloat(
      3,
      f
    );
  }
  f = message.getVelocityMps();
  if (f !== 0.0) {
    writer.writeFloat(
      4,
      f
    );
  }
  f = message.getTimestampMs();
  if (f !== 0) {
    writer.writeUint64(
      5,
      f
    );
  }
};


/**
 * optional double latitude_deg = 1;
 * @return {number}
 */
proto.project.tracknest.usertracking.proto.v1.UpdateUserLocationRequest.prototype.getLatitudeDeg = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 1, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.project.tracknest.usertracking.proto.v1.UpdateUserLocationRequest} returns this
 */
proto.project.tracknest.usertracking.proto.v1.UpdateUserLocationRequest.prototype.setLatitudeDeg = function(value) {
  return jspb.Message.setProto3FloatField(this, 1, value);
};


/**
 * optional double longitude_deg = 2;
 * @return {number}
 */
proto.project.tracknest.usertracking.proto.v1.UpdateUserLocationRequest.prototype.getLongitudeDeg = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 2, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.project.tracknest.usertracking.proto.v1.UpdateUserLocationRequest} returns this
 */
proto.project.tracknest.usertracking.proto.v1.UpdateUserLocationRequest.prototype.setLongitudeDeg = function(value) {
  return jspb.Message.setProto3FloatField(this, 2, value);
};


/**
 * optional float accuracy_meter = 3;
 * @return {number}
 */
proto.project.tracknest.usertracking.proto.v1.UpdateUserLocationRequest.prototype.getAccuracyMeter = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 3, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.project.tracknest.usertracking.proto.v1.UpdateUserLocationRequest} returns this
 */
proto.project.tracknest.usertracking.proto.v1.UpdateUserLocationRequest.prototype.setAccuracyMeter = function(value) {
  return jspb.Message.setProto3FloatField(this, 3, value);
};


/**
 * optional float velocity_mps = 4;
 * @return {number}
 */
proto.project.tracknest.usertracking.proto.v1.UpdateUserLocationRequest.prototype.getVelocityMps = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 4, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.project.tracknest.usertracking.proto.v1.UpdateUserLocationRequest} returns this
 */
proto.project.tracknest.usertracking.proto.v1.UpdateUserLocationRequest.prototype.setVelocityMps = function(value) {
  return jspb.Message.setProto3FloatField(this, 4, value);
};


/**
 * optional uint64 timestamp_ms = 5;
 * @return {number}
 */
proto.project.tracknest.usertracking.proto.v1.UpdateUserLocationRequest.prototype.getTimestampMs = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 5, 0));
};


/**
 * @param {number} value
 * @return {!proto.project.tracknest.usertracking.proto.v1.UpdateUserLocationRequest} returns this
 */
proto.project.tracknest.usertracking.proto.v1.UpdateUserLocationRequest.prototype.setTimestampMs = function(value) {
  return jspb.Message.setProto3IntField(this, 5, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.project.tracknest.usertracking.proto.v1.UpdateUserLocationResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.project.tracknest.usertracking.proto.v1.UpdateUserLocationResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.project.tracknest.usertracking.proto.v1.UpdateUserLocationResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.project.tracknest.usertracking.proto.v1.UpdateUserLocationResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
status: (f = msg.getStatus()) && google_rpc_status_pb.Status.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.project.tracknest.usertracking.proto.v1.UpdateUserLocationResponse}
 */
proto.project.tracknest.usertracking.proto.v1.UpdateUserLocationResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.project.tracknest.usertracking.proto.v1.UpdateUserLocationResponse;
  return proto.project.tracknest.usertracking.proto.v1.UpdateUserLocationResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.project.tracknest.usertracking.proto.v1.UpdateUserLocationResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.project.tracknest.usertracking.proto.v1.UpdateUserLocationResponse}
 */
proto.project.tracknest.usertracking.proto.v1.UpdateUserLocationResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new google_rpc_status_pb.Status;
      reader.readMessage(value,google_rpc_status_pb.Status.deserializeBinaryFromReader);
      msg.setStatus(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.project.tracknest.usertracking.proto.v1.UpdateUserLocationResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.project.tracknest.usertracking.proto.v1.UpdateUserLocationResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.project.tracknest.usertracking.proto.v1.UpdateUserLocationResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.project.tracknest.usertracking.proto.v1.UpdateUserLocationResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getStatus();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      google_rpc_status_pb.Status.serializeBinaryToWriter
    );
  }
};


/**
 * optional google.rpc.Status status = 1;
 * @return {?proto.google.rpc.Status}
 */
proto.project.tracknest.usertracking.proto.v1.UpdateUserLocationResponse.prototype.getStatus = function() {
  return /** @type{?proto.google.rpc.Status} */ (
    jspb.Message.getWrapperField(this, google_rpc_status_pb.Status, 1));
};


/**
 * @param {?proto.google.rpc.Status|undefined} value
 * @return {!proto.project.tracknest.usertracking.proto.v1.UpdateUserLocationResponse} returns this
*/
proto.project.tracknest.usertracking.proto.v1.UpdateUserLocationResponse.prototype.setStatus = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.project.tracknest.usertracking.proto.v1.UpdateUserLocationResponse} returns this
 */
proto.project.tracknest.usertracking.proto.v1.UpdateUserLocationResponse.prototype.clearStatus = function() {
  return this.setStatus(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.project.tracknest.usertracking.proto.v1.UpdateUserLocationResponse.prototype.hasStatus = function() {
  return jspb.Message.getField(this, 1) != null;
};


goog.object.extend(exports, proto.project.tracknest.usertracking.proto.v1);
