/**
 * @fileoverview gRPC-Web generated client stub for project.tracknest.usertracking.proto.v1
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v2.0.2
// 	protoc              v6.33.2
// source: tracker.proto


/* eslint-disable */
// @ts-nocheck


import * as grpcWeb from 'grpc-web';

import * as tracker_pb from './tracker_pb'; // proto import: "tracker.proto"


export class TrackerControllerClient {
  client_: grpcWeb.AbstractClientBase;
  hostname_: string;
  credentials_: null | { [index: string]: string; };
  options_: null | { [index: string]: any; };

  constructor (hostname: string,
               credentials?: null | { [index: string]: string; },
               options?: null | { [index: string]: any; }) {
    if (!options) options = {};
    if (!credentials) credentials = {};
    options['format'] = 'text';

    this.client_ = new grpcWeb.GrpcWebClientBase(options);
    this.hostname_ = hostname.replace(/\/+$/, '');
    this.credentials_ = credentials;
    this.options_ = options;
  }

  methodDescriptorStreamFamilyMemberLocations = new grpcWeb.MethodDescriptor(
    '/project.tracknest.usertracking.proto.v1.TrackerController/StreamFamilyMemberLocations',
    grpcWeb.MethodType.SERVER_STREAMING,
    tracker_pb.StreamFamilyMemberLocationsRequest,
    tracker_pb.FamilyMemberLocation,
    (request: tracker_pb.StreamFamilyMemberLocationsRequest) => {
      return request.serializeBinary();
    },
    tracker_pb.FamilyMemberLocation.deserializeBinary
  );

  streamFamilyMemberLocations(
    request: tracker_pb.StreamFamilyMemberLocationsRequest,
    metadata?: grpcWeb.Metadata): grpcWeb.ClientReadableStream<tracker_pb.FamilyMemberLocation> {
    return this.client_.serverStreaming(
      this.hostname_ +
        '/project.tracknest.usertracking.proto.v1.TrackerController/StreamFamilyMemberLocations',
      request,
      metadata || {},
      this.methodDescriptorStreamFamilyMemberLocations);
  }

  methodDescriptorListFamilyMemberLocationHistory = new grpcWeb.MethodDescriptor(
    '/project.tracknest.usertracking.proto.v1.TrackerController/ListFamilyMemberLocationHistory',
    grpcWeb.MethodType.UNARY,
    tracker_pb.ListFamilyMemberLocationHistoryRequest,
    tracker_pb.ListFamilyMemberLocationHistoryResponse,
    (request: tracker_pb.ListFamilyMemberLocationHistoryRequest) => {
      return request.serializeBinary();
    },
    tracker_pb.ListFamilyMemberLocationHistoryResponse.deserializeBinary
  );

  listFamilyMemberLocationHistory(
    request: tracker_pb.ListFamilyMemberLocationHistoryRequest,
    metadata?: grpcWeb.Metadata | null): Promise<tracker_pb.ListFamilyMemberLocationHistoryResponse>;

  listFamilyMemberLocationHistory(
    request: tracker_pb.ListFamilyMemberLocationHistoryRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: tracker_pb.ListFamilyMemberLocationHistoryResponse) => void): grpcWeb.ClientReadableStream<tracker_pb.ListFamilyMemberLocationHistoryResponse>;

  listFamilyMemberLocationHistory(
    request: tracker_pb.ListFamilyMemberLocationHistoryRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: tracker_pb.ListFamilyMemberLocationHistoryResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/project.tracknest.usertracking.proto.v1.TrackerController/ListFamilyMemberLocationHistory',
        request,
        metadata || {},
        this.methodDescriptorListFamilyMemberLocationHistory,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/project.tracknest.usertracking.proto.v1.TrackerController/ListFamilyMemberLocationHistory',
    request,
    metadata || {},
    this.methodDescriptorListFamilyMemberLocationHistory);
  }

}

