/**
 * @fileoverview gRPC-Web generated client stub for project.tracknest.usertracking.proto
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v2.0.2
// 	protoc              v6.33.2
// source: tracker.proto


/* eslint-disable */
// @ts-nocheck


import * as grpcWeb from 'grpc-web';

import * as google_protobuf_empty_pb from 'google-protobuf/google/protobuf/empty_pb'; // proto import: "google/protobuf/empty.proto"
import * as tracker_pb from './tracker_pb'; // proto import: "tracker.proto"


export class TrackerControllerClient {
  client_: grpcWeb.AbstractClientBase;
  hostname_: string;
  credentials_: null | { [index: string]: string; };
  options_: null | { [index: string]: any; };

  constructor (hostname: string,
               credentials?: null | { [index: string]: string; },
               options?: null | { [index: string]: any; }) {
    if (!options) options = {};
    if (!credentials) credentials = {};
    options['format'] = 'text';

    this.client_ = new grpcWeb.GrpcWebClientBase(options);
    this.hostname_ = hostname.replace(/\/+$/, '');
    this.credentials_ = credentials;
    this.options_ = options;
  }

  methodDescriptorgetTargetsLastLocations = new grpcWeb.MethodDescriptor(
    '/project.tracknest.usertracking.proto.TrackerController/getTargetsLastLocations',
    grpcWeb.MethodType.SERVER_STREAMING,
    google_protobuf_empty_pb.Empty,
    tracker_pb.LocationResponse,
    (request: google_protobuf_empty_pb.Empty) => {
      return request.serializeBinary();
    },
    tracker_pb.LocationResponse.deserializeBinary
  );

  getTargetsLastLocations(
    request: google_protobuf_empty_pb.Empty,
    metadata?: grpcWeb.Metadata): grpcWeb.ClientReadableStream<tracker_pb.LocationResponse> {
    return this.client_.serverStreaming(
      this.hostname_ +
        '/project.tracknest.usertracking.proto.TrackerController/getTargetsLastLocations',
      request,
      metadata || {},
      this.methodDescriptorgetTargetsLastLocations);
  }

  methodDescriptorgetTargetLocationHistory = new grpcWeb.MethodDescriptor(
    '/project.tracknest.usertracking.proto.TrackerController/getTargetLocationHistory',
    grpcWeb.MethodType.SERVER_STREAMING,
    tracker_pb.LocationHistoryRequest,
    tracker_pb.LocationResponse,
    (request: tracker_pb.LocationHistoryRequest) => {
      return request.serializeBinary();
    },
    tracker_pb.LocationResponse.deserializeBinary
  );

  getTargetLocationHistory(
    request: tracker_pb.LocationHistoryRequest,
    metadata?: grpcWeb.Metadata): grpcWeb.ClientReadableStream<tracker_pb.LocationResponse> {
    return this.client_.serverStreaming(
      this.hostname_ +
        '/project.tracknest.usertracking.proto.TrackerController/getTargetLocationHistory',
      request,
      metadata || {},
      this.methodDescriptorgetTargetLocationHistory);
  }

}

