/**
 * @fileoverview gRPC-Web generated client stub for project.tracknest.usertracking.proto.v1
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v2.0.2
// 	protoc              v6.33.2
// source: trackingmanager.proto


/* eslint-disable */
// @ts-nocheck


import * as grpcWeb from 'grpc-web';

import * as trackingmanager_pb from './trackingmanager_pb'; // proto import: "trackingmanager.proto"


export class TrackingManagerControllerClient {
  client_: grpcWeb.AbstractClientBase;
  hostname_: string;
  credentials_: null | { [index: string]: string; };
  options_: null | { [index: string]: any; };

  constructor (hostname: string,
               credentials?: null | { [index: string]: string; },
               options?: null | { [index: string]: any; }) {
    if (!options) options = {};
    if (!credentials) credentials = {};
    options['format'] = 'text';

    this.client_ = new grpcWeb.GrpcWebClientBase(options);
    this.hostname_ = hostname.replace(/\/+$/, '');
    this.credentials_ = credentials;
    this.options_ = options;
  }

  methodDescriptorCreateFamilyCircle = new grpcWeb.MethodDescriptor(
    '/project.tracknest.usertracking.proto.v1.TrackingManagerController/CreateFamilyCircle',
    grpcWeb.MethodType.UNARY,
    trackingmanager_pb.CreateFamilyCircleRequest,
    trackingmanager_pb.CreateFamilyCircleResponse,
    (request: trackingmanager_pb.CreateFamilyCircleRequest) => {
      return request.serializeBinary();
    },
    trackingmanager_pb.CreateFamilyCircleResponse.deserializeBinary
  );

  createFamilyCircle(
    request: trackingmanager_pb.CreateFamilyCircleRequest,
    metadata?: grpcWeb.Metadata | null): Promise<trackingmanager_pb.CreateFamilyCircleResponse>;

  createFamilyCircle(
    request: trackingmanager_pb.CreateFamilyCircleRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: trackingmanager_pb.CreateFamilyCircleResponse) => void): grpcWeb.ClientReadableStream<trackingmanager_pb.CreateFamilyCircleResponse>;

  createFamilyCircle(
    request: trackingmanager_pb.CreateFamilyCircleRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: trackingmanager_pb.CreateFamilyCircleResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/project.tracknest.usertracking.proto.v1.TrackingManagerController/CreateFamilyCircle',
        request,
        metadata || {},
        this.methodDescriptorCreateFamilyCircle,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/project.tracknest.usertracking.proto.v1.TrackingManagerController/CreateFamilyCircle',
    request,
    metadata || {},
    this.methodDescriptorCreateFamilyCircle);
  }

  methodDescriptorListFamilyCircles = new grpcWeb.MethodDescriptor(
    '/project.tracknest.usertracking.proto.v1.TrackingManagerController/ListFamilyCircles',
    grpcWeb.MethodType.UNARY,
    trackingmanager_pb.ListFamilyCirclesRequest,
    trackingmanager_pb.ListFamilyCircleResponse,
    (request: trackingmanager_pb.ListFamilyCirclesRequest) => {
      return request.serializeBinary();
    },
    trackingmanager_pb.ListFamilyCircleResponse.deserializeBinary
  );

  listFamilyCircles(
    request: trackingmanager_pb.ListFamilyCirclesRequest,
    metadata?: grpcWeb.Metadata | null): Promise<trackingmanager_pb.ListFamilyCircleResponse>;

  listFamilyCircles(
    request: trackingmanager_pb.ListFamilyCirclesRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: trackingmanager_pb.ListFamilyCircleResponse) => void): grpcWeb.ClientReadableStream<trackingmanager_pb.ListFamilyCircleResponse>;

  listFamilyCircles(
    request: trackingmanager_pb.ListFamilyCirclesRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: trackingmanager_pb.ListFamilyCircleResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/project.tracknest.usertracking.proto.v1.TrackingManagerController/ListFamilyCircles',
        request,
        metadata || {},
        this.methodDescriptorListFamilyCircles,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/project.tracknest.usertracking.proto.v1.TrackingManagerController/ListFamilyCircles',
    request,
    metadata || {},
    this.methodDescriptorListFamilyCircles);
  }

  methodDescriptorDeleteFamilyCircle = new grpcWeb.MethodDescriptor(
    '/project.tracknest.usertracking.proto.v1.TrackingManagerController/DeleteFamilyCircle',
    grpcWeb.MethodType.UNARY,
    trackingmanager_pb.DeleteFamilyCircleRequest,
    trackingmanager_pb.DeleteFamilyCircleResponse,
    (request: trackingmanager_pb.DeleteFamilyCircleRequest) => {
      return request.serializeBinary();
    },
    trackingmanager_pb.DeleteFamilyCircleResponse.deserializeBinary
  );

  deleteFamilyCircle(
    request: trackingmanager_pb.DeleteFamilyCircleRequest,
    metadata?: grpcWeb.Metadata | null): Promise<trackingmanager_pb.DeleteFamilyCircleResponse>;

  deleteFamilyCircle(
    request: trackingmanager_pb.DeleteFamilyCircleRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: trackingmanager_pb.DeleteFamilyCircleResponse) => void): grpcWeb.ClientReadableStream<trackingmanager_pb.DeleteFamilyCircleResponse>;

  deleteFamilyCircle(
    request: trackingmanager_pb.DeleteFamilyCircleRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: trackingmanager_pb.DeleteFamilyCircleResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/project.tracknest.usertracking.proto.v1.TrackingManagerController/DeleteFamilyCircle',
        request,
        metadata || {},
        this.methodDescriptorDeleteFamilyCircle,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/project.tracknest.usertracking.proto.v1.TrackingManagerController/DeleteFamilyCircle',
    request,
    metadata || {},
    this.methodDescriptorDeleteFamilyCircle);
  }

  methodDescriptorUpdateFamilyCircle = new grpcWeb.MethodDescriptor(
    '/project.tracknest.usertracking.proto.v1.TrackingManagerController/UpdateFamilyCircle',
    grpcWeb.MethodType.UNARY,
    trackingmanager_pb.UpdateFamilyCircleRequest,
    trackingmanager_pb.UpdateFamilyCircleResponse,
    (request: trackingmanager_pb.UpdateFamilyCircleRequest) => {
      return request.serializeBinary();
    },
    trackingmanager_pb.UpdateFamilyCircleResponse.deserializeBinary
  );

  updateFamilyCircle(
    request: trackingmanager_pb.UpdateFamilyCircleRequest,
    metadata?: grpcWeb.Metadata | null): Promise<trackingmanager_pb.UpdateFamilyCircleResponse>;

  updateFamilyCircle(
    request: trackingmanager_pb.UpdateFamilyCircleRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: trackingmanager_pb.UpdateFamilyCircleResponse) => void): grpcWeb.ClientReadableStream<trackingmanager_pb.UpdateFamilyCircleResponse>;

  updateFamilyCircle(
    request: trackingmanager_pb.UpdateFamilyCircleRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: trackingmanager_pb.UpdateFamilyCircleResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/project.tracknest.usertracking.proto.v1.TrackingManagerController/UpdateFamilyCircle',
        request,
        metadata || {},
        this.methodDescriptorUpdateFamilyCircle,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/project.tracknest.usertracking.proto.v1.TrackingManagerController/UpdateFamilyCircle',
    request,
    metadata || {},
    this.methodDescriptorUpdateFamilyCircle);
  }

  methodDescriptorUpdateFamilyRole = new grpcWeb.MethodDescriptor(
    '/project.tracknest.usertracking.proto.v1.TrackingManagerController/UpdateFamilyRole',
    grpcWeb.MethodType.UNARY,
    trackingmanager_pb.UpdateFamilyRoleRequest,
    trackingmanager_pb.UpdateFamilyRoleResponse,
    (request: trackingmanager_pb.UpdateFamilyRoleRequest) => {
      return request.serializeBinary();
    },
    trackingmanager_pb.UpdateFamilyRoleResponse.deserializeBinary
  );

  updateFamilyRole(
    request: trackingmanager_pb.UpdateFamilyRoleRequest,
    metadata?: grpcWeb.Metadata | null): Promise<trackingmanager_pb.UpdateFamilyRoleResponse>;

  updateFamilyRole(
    request: trackingmanager_pb.UpdateFamilyRoleRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: trackingmanager_pb.UpdateFamilyRoleResponse) => void): grpcWeb.ClientReadableStream<trackingmanager_pb.UpdateFamilyRoleResponse>;

  updateFamilyRole(
    request: trackingmanager_pb.UpdateFamilyRoleRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: trackingmanager_pb.UpdateFamilyRoleResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/project.tracknest.usertracking.proto.v1.TrackingManagerController/UpdateFamilyRole',
        request,
        metadata || {},
        this.methodDescriptorUpdateFamilyRole,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/project.tracknest.usertracking.proto.v1.TrackingManagerController/UpdateFamilyRole',
    request,
    metadata || {},
    this.methodDescriptorUpdateFamilyRole);
  }

  methodDescriptorCreateParticipationPermission = new grpcWeb.MethodDescriptor(
    '/project.tracknest.usertracking.proto.v1.TrackingManagerController/CreateParticipationPermission',
    grpcWeb.MethodType.UNARY,
    trackingmanager_pb.CreateParticipationPermissionRequest,
    trackingmanager_pb.CreateParticipationPermissionResponse,
    (request: trackingmanager_pb.CreateParticipationPermissionRequest) => {
      return request.serializeBinary();
    },
    trackingmanager_pb.CreateParticipationPermissionResponse.deserializeBinary
  );

  createParticipationPermission(
    request: trackingmanager_pb.CreateParticipationPermissionRequest,
    metadata?: grpcWeb.Metadata | null): Promise<trackingmanager_pb.CreateParticipationPermissionResponse>;

  createParticipationPermission(
    request: trackingmanager_pb.CreateParticipationPermissionRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: trackingmanager_pb.CreateParticipationPermissionResponse) => void): grpcWeb.ClientReadableStream<trackingmanager_pb.CreateParticipationPermissionResponse>;

  createParticipationPermission(
    request: trackingmanager_pb.CreateParticipationPermissionRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: trackingmanager_pb.CreateParticipationPermissionResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/project.tracknest.usertracking.proto.v1.TrackingManagerController/CreateParticipationPermission',
        request,
        metadata || {},
        this.methodDescriptorCreateParticipationPermission,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/project.tracknest.usertracking.proto.v1.TrackingManagerController/CreateParticipationPermission',
    request,
    metadata || {},
    this.methodDescriptorCreateParticipationPermission);
  }

  methodDescriptorParticipateInFamilyCircle = new grpcWeb.MethodDescriptor(
    '/project.tracknest.usertracking.proto.v1.TrackingManagerController/ParticipateInFamilyCircle',
    grpcWeb.MethodType.UNARY,
    trackingmanager_pb.ParticipateInFamilyCircleRequest,
    trackingmanager_pb.ParticipateInFamilyCircleResponse,
    (request: trackingmanager_pb.ParticipateInFamilyCircleRequest) => {
      return request.serializeBinary();
    },
    trackingmanager_pb.ParticipateInFamilyCircleResponse.deserializeBinary
  );

  participateInFamilyCircle(
    request: trackingmanager_pb.ParticipateInFamilyCircleRequest,
    metadata?: grpcWeb.Metadata | null): Promise<trackingmanager_pb.ParticipateInFamilyCircleResponse>;

  participateInFamilyCircle(
    request: trackingmanager_pb.ParticipateInFamilyCircleRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: trackingmanager_pb.ParticipateInFamilyCircleResponse) => void): grpcWeb.ClientReadableStream<trackingmanager_pb.ParticipateInFamilyCircleResponse>;

  participateInFamilyCircle(
    request: trackingmanager_pb.ParticipateInFamilyCircleRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: trackingmanager_pb.ParticipateInFamilyCircleResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/project.tracknest.usertracking.proto.v1.TrackingManagerController/ParticipateInFamilyCircle',
        request,
        metadata || {},
        this.methodDescriptorParticipateInFamilyCircle,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/project.tracknest.usertracking.proto.v1.TrackingManagerController/ParticipateInFamilyCircle',
    request,
    metadata || {},
    this.methodDescriptorParticipateInFamilyCircle);
  }

  methodDescriptorLeaveFamilyCircle = new grpcWeb.MethodDescriptor(
    '/project.tracknest.usertracking.proto.v1.TrackingManagerController/LeaveFamilyCircle',
    grpcWeb.MethodType.UNARY,
    trackingmanager_pb.LeaveFamilyCircleRequest,
    trackingmanager_pb.LeaveFamilyCircleResponse,
    (request: trackingmanager_pb.LeaveFamilyCircleRequest) => {
      return request.serializeBinary();
    },
    trackingmanager_pb.LeaveFamilyCircleResponse.deserializeBinary
  );

  leaveFamilyCircle(
    request: trackingmanager_pb.LeaveFamilyCircleRequest,
    metadata?: grpcWeb.Metadata | null): Promise<trackingmanager_pb.LeaveFamilyCircleResponse>;

  leaveFamilyCircle(
    request: trackingmanager_pb.LeaveFamilyCircleRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: trackingmanager_pb.LeaveFamilyCircleResponse) => void): grpcWeb.ClientReadableStream<trackingmanager_pb.LeaveFamilyCircleResponse>;

  leaveFamilyCircle(
    request: trackingmanager_pb.LeaveFamilyCircleRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: trackingmanager_pb.LeaveFamilyCircleResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/project.tracknest.usertracking.proto.v1.TrackingManagerController/LeaveFamilyCircle',
        request,
        metadata || {},
        this.methodDescriptorLeaveFamilyCircle,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/project.tracknest.usertracking.proto.v1.TrackingManagerController/LeaveFamilyCircle',
    request,
    metadata || {},
    this.methodDescriptorLeaveFamilyCircle);
  }

  methodDescriptorRemoveMemberFromFamilyCircle = new grpcWeb.MethodDescriptor(
    '/project.tracknest.usertracking.proto.v1.TrackingManagerController/RemoveMemberFromFamilyCircle',
    grpcWeb.MethodType.UNARY,
    trackingmanager_pb.RemoveMemberFromFamilyCircleRequest,
    trackingmanager_pb.RemoveMemberFromFamilyCircleResponse,
    (request: trackingmanager_pb.RemoveMemberFromFamilyCircleRequest) => {
      return request.serializeBinary();
    },
    trackingmanager_pb.RemoveMemberFromFamilyCircleResponse.deserializeBinary
  );

  removeMemberFromFamilyCircle(
    request: trackingmanager_pb.RemoveMemberFromFamilyCircleRequest,
    metadata?: grpcWeb.Metadata | null): Promise<trackingmanager_pb.RemoveMemberFromFamilyCircleResponse>;

  removeMemberFromFamilyCircle(
    request: trackingmanager_pb.RemoveMemberFromFamilyCircleRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: trackingmanager_pb.RemoveMemberFromFamilyCircleResponse) => void): grpcWeb.ClientReadableStream<trackingmanager_pb.RemoveMemberFromFamilyCircleResponse>;

  removeMemberFromFamilyCircle(
    request: trackingmanager_pb.RemoveMemberFromFamilyCircleRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: trackingmanager_pb.RemoveMemberFromFamilyCircleResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/project.tracknest.usertracking.proto.v1.TrackingManagerController/RemoveMemberFromFamilyCircle',
        request,
        metadata || {},
        this.methodDescriptorRemoveMemberFromFamilyCircle,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/project.tracknest.usertracking.proto.v1.TrackingManagerController/RemoveMemberFromFamilyCircle',
    request,
    metadata || {},
    this.methodDescriptorRemoveMemberFromFamilyCircle);
  }

  methodDescriptorAssignFamilyCircleAdmin = new grpcWeb.MethodDescriptor(
    '/project.tracknest.usertracking.proto.v1.TrackingManagerController/AssignFamilyCircleAdmin',
    grpcWeb.MethodType.UNARY,
    trackingmanager_pb.AssignFamilyCircleAdminRequest,
    trackingmanager_pb.AssignFamilyCircleAdminResponse,
    (request: trackingmanager_pb.AssignFamilyCircleAdminRequest) => {
      return request.serializeBinary();
    },
    trackingmanager_pb.AssignFamilyCircleAdminResponse.deserializeBinary
  );

  assignFamilyCircleAdmin(
    request: trackingmanager_pb.AssignFamilyCircleAdminRequest,
    metadata?: grpcWeb.Metadata | null): Promise<trackingmanager_pb.AssignFamilyCircleAdminResponse>;

  assignFamilyCircleAdmin(
    request: trackingmanager_pb.AssignFamilyCircleAdminRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: trackingmanager_pb.AssignFamilyCircleAdminResponse) => void): grpcWeb.ClientReadableStream<trackingmanager_pb.AssignFamilyCircleAdminResponse>;

  assignFamilyCircleAdmin(
    request: trackingmanager_pb.AssignFamilyCircleAdminRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: trackingmanager_pb.AssignFamilyCircleAdminResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/project.tracknest.usertracking.proto.v1.TrackingManagerController/AssignFamilyCircleAdmin',
        request,
        metadata || {},
        this.methodDescriptorAssignFamilyCircleAdmin,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/project.tracknest.usertracking.proto.v1.TrackingManagerController/AssignFamilyCircleAdmin',
    request,
    metadata || {},
    this.methodDescriptorAssignFamilyCircleAdmin);
  }

}

