routes:
  - uri: /*
    plugins:
      openid-connect:
        client_id: "tracknest"
        client_secret: "5YgzCDGJLO0uXBhkGMyeJjHE1CKUt4fJ"
        discovery: "http://keycloak:8080/realms/tracknest-user/.well-known/openid-configuration"
        introspection_endpoint: "http://keycloak:8080/realms/tracknest-user/protocol/openid-connect/token/introspect"
        scope: "openid profile"
        realm: "tracknest-user"
        bearer_only: true
    upstream:
      scheme: "grpc"
      type: roundrobin
      nodes:
        "host.docker.internal:19090": 1
#END