ALTER TABLE crime_report ADD COLUMN IF NOT EXISTS submitted_by_user BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE missing_person_report ADD COLUMN IF NOT EXISTS submitted_by_user BOOLEAN NOT NULL DEFAULT FALSE;
