apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-envoy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: envoy
  template:
    metadata:
      labels:
        app: envoy
    spec:
      containers:
        - name: envoy
          image: "{{ .Values.envoy.image.repository }}:{{ .Values.envoy.image.tag }}"
          ports:
            - containerPort: {{ .Values.envoy.port }}
            - containerPort: {{ .Values.envoy.adminPort }}

          volumeMounts:
            - name: envoy-config
              mountPath: /etc/envoy
              readOnly: true
            - name: cf-cert
              mountPath: /etc/ssl
              readOnly: true

      volumes:
        - name: envoy-config
          configMap:
            name: envoy-config
        - name: cf-cert
          secret:
            secretName: cf-cert