apiVersion: v1
kind: Service
metadata:
  name: envoy
spec:
  type: ClusterIP
  selector:
    app: envoy
  ports:
    - name: api
      port: 8800
      targetPort: {{ .Values.envoy.port }}

    - name: admin
      port: 9901
      targetPort: {{ .Values.envoy.adminPort }}