apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-nginx
  labels:
    {{- include "gateway.nginxLabels" . | nindent 4 }}
spec:
  replicas: {{ .Values.nginx.replicaCount }}
  revisionHistoryLimit: {{ .Values.nginx.revisionHistoryLimit }}
  strategy:
    {{- toYaml .Values.nginx.strategy | nindent 4 }}
  selector:
    matchLabels:
      {{- include "gateway.nginxSelector" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "gateway.nginxSelector" . | nindent 8 }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/nginx-configmap.yaml") . | sha256sum }}
    spec:
      terminationGracePeriodSeconds: {{ .Values.nginx.terminationGracePeriodSeconds }}
      securityContext:
        {{- toYaml .Values.nginx.podSecurityContext | nindent 8 }}
      containers:
        - name: nginx
          image: "{{ .Values.nginx.image.repository }}:{{ .Values.nginx.image.tag }}"
          imagePullPolicy: {{ .Values.nginx.image.pullPolicy }}
          securityContext:
            {{- toYaml .Values.nginx.containerSecurityContext | nindent 12 }}
          resources:
            {{- toYaml .Values.nginx.resources | nindent 12 }}
          ports:
            - name: http
              containerPort: {{ .Values.nginx.plainPort }}
              protocol: TCP
            - name: https
              containerPort: {{ .Values.nginx.port }}
              protocol: TCP
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
            - name: cf-cert
              mountPath: /etc/nginx/ssl
              readOnly: true
          livenessProbe:
            tcpSocket:
              port: https
            initialDelaySeconds: 10
            periodSeconds: 20
          readinessProbe:
            tcpSocket:
              port: https
            initialDelaySeconds: 5
            periodSeconds: 10
      volumes:
        - name: nginx-config
          configMap:
            name: nginx-config
        - name: cf-cert
          secret:
            secretName: {{ .Values.tlsSecretName }}
