apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    {{- include "gateway.nginxLabels" . | nindent 4 }}
spec:
  type: {{ .Values.nginx.serviceType }}
  selector:
    {{- include "gateway.nginxSelector" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.nginx.plainServicePort }}
      targetPort: http
      protocol: TCP
    - name: https
      port: {{ .Values.nginx.servicePort }}
      targetPort: https
      protocol: TCP
