apiVersion: v1
kind: Service
metadata:
  name: keycloak
  labels:
    app: keycloak
spec:
  type: ClusterIP
  selector:
    app: keycloak
  ports:
    - name: http
      port: {{ .Values.keycloak.port }}
      targetPort: {{ .Values.keycloak.port }}

    - name: management
      port: {{ .Values.keycloak.managementPort }}
      targetPort: {{ .Values.keycloak.managementPort }}