apiVersion: v1
kind: ConfigMap
metadata:
  name: keycloak-realm-config
  labels:
    {{- include "keycloak.labels" . | nindent 4 }}
data:
  public-dev.json: |
    {{ .Files.Get (printf "realms/%s" .Values.keycloak.realmFiles.public) | nindent 4 }}

  restricted-dev.json: |
    {{ .Files.Get (printf "realms/%s" .Values.keycloak.realmFiles.restricted) | nindent 4 }}
