apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: keycloak-alerts
  namespace: {{ .Release.Namespace }}
  labels:
    release: {{ .Release.Name }}
spec:
  groups:
    - name: keycloak.rules
      rules:

        # 🔴 Service down
        - alert: KeycloakDown
          expr: up{job="keycloak"} == 0
          for: 1m
          labels:
            severity: critical
          annotations:
            summary: "Keycloak is down"

        - alert: KeycloakHighErrorRate
          expr: |
            sum(rate(http_server_requests_seconds_count{job="keycloak", status=~"5.."}[2m]))
            /
            sum(rate(http_server_requests_seconds_count{job="keycloak"}[2m]))
            > 0.05
          for: 2m
          labels:
            severity: warning
          annotations:
            summary: "Keycloak error rate > 5%"

        - alert: KeycloakHighLatency
          expr: |
            histogram_quantile(0.95,
              sum(rate(http_server_requests_seconds_bucket{job="keycloak"}[5m])) by (le)
            ) > 1
          for: 2m
          labels:
            severity: warning
          annotations:
            summary: "Keycloak latency high (P95 > 1s)"

        - alert: KeycloakHighMemory
          expr: |
            jvm_memory_used_bytes{job="keycloak", area="heap"}
            /
            jvm_memory_max_bytes{job="keycloak", area="heap"}
            > 0.9
          for: 2m
          labels:
            severity: warning
          annotations:
            summary: "Keycloak heap usage > 90%"