apiVersion: v1
kind: Service
metadata:
  name: keycloak
  labels:
    {{- include "keycloak.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "keycloak.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.keycloak.port }}
      targetPort: http
      protocol: TCP
    - name: management
      port: {{ .Values.keycloak.managementPort }}
      targetPort: management
      protocol: TCP
