apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: criminal-reports-monitor
  namespace: {{ .Release.Namespace }}
  labels:
    release: {{ .Release.Name }}
spec:
  selector:
    matchLabels:
      app: criminal-reports
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  endpoints:
    - port: management
      path: /actuator/prometheus
      interval: 15s