apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: criminal-reports-alerts
  namespace: {{ .Release.Namespace }}
  labels:
    release: {{ .Release.Name }}
spec:
  groups:
    - name: criminal-reports.rules
      rules:
        - alert: HighErrorRate
          expr: |
            sum(rate(http_server_requests_seconds_count{job="criminal-reports", status=~"5.."}[1m]))
            /
            sum(rate(http_server_requests_seconds_count{job="criminal-reports"}[1m]))
            > 0.05
          for: 2m
          labels:
            severity: warning
          annotations:
            summary: "High error rate"

        - alert: HighLatency
          expr: |
            histogram_quantile(0.95,
              sum(rate(http_server_requests_seconds_bucket{job="criminal-reports"}[5m])) by (le)
            ) > 0.5
          for: 2m
          labels:
            severity: warning
          annotations:
            summary: "High latency"

        - alert: PodDown
          expr: |
            up{job="criminal-reports"} == 0
          for: 1m
          labels:
            severity: critical
          annotations:
            summary: "Pod down"