apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: emergency-ops-monitor
  namespace: {{ .Release.Namespace }}
  labels:
    release: {{ .Release.Name }}
spec:
  selector:
    matchLabels:
      app: emergency-ops
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  endpoints:
    - port: management
      path: /actuator/prometheus
      interval: 15s