services:
  ### CRIMINAL INFORMATION SERVICE ###
  criminal-info-postgres:
    image: postgres:latest
    container_name: criminal-info-postgres
    environment:
      POSTGRES_USER: postgresadmin
      POSTGRES_PASSWORD: postgresadmin
      POSTGRES_DB: CRIMINAL_INFO
    ports:
      - "10000:5432"
    volumes:
      - criminal-info-postgres-data:/var/lib/postgresql/data
      - ../migration/postgres/01-criminal-info-schema.sql:/docker-entrypoint-initdb.d/01-schema.sql
      - ../migration/postgres/02-criminal-info-seeding.sql:/docker-entrypoint-initdb.d/02-seeding.sql
    networks:
      - tracknest-network
    
  criminal-info-minio:
    image: minio/minio
    container_name: criminal-info-minio
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
      MINIO_VOLUMES: /mnt/data
      MINIO_OPTS: "--console-address :9001"
    ports:
      - "11000:9000"
      - "11001:9001"
    volumes:
      - criminal-info-minio-data:/mnt/data
    command: server --console-address ":9001"
    networks:
      - tracknest-network

  criminal-info-service:
    build:
      context: ../services/criminal-info-service
      dockerfile: Dockerfile
    ports:
      - "12000:12000"
    environment:
      SPRING_PROFILES_ACTIVE: container
    networks:
      - tracknest-network

  ### LOCATION TRACKING SERVICE ###
  location-tracking-postgres:
    image: postgres:latest
    container_name: location-tracking-postgres
    environment:
      POSTGRES_USER: postgresadmin
      POSTGRES_PASSWORD: postgresadmin
      POSTGRES_DB: LOCATION_TRACKING
    ports:
      - "13000:5432"
    volumes:
      - location-tracking-postgres-data:/var/lib/postgresql/data
      - ../migration/postgres/01-location-tracking-schema.sql:/docker-entrypoint-initdb.d/01-schema.sql
      - ../migration/postgres/02-location-tracking-seeding.sql:/docker-entrypoint-initdb.d/02-seeding.sql
    networks:
      - tracknest-network
  
  location-tracking-minio:
    image: minio/minio
    container_name: location-tracking-minio
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
      MINIO_VOLUMES: /mnt/data
      MINIO_OPTS: "--console-address :9001"
    ports:
      - "14000:9000"
      - "14001:9001"
    volumes:
      - location-tracking-minio-data:/mnt/data
    command: server --console-address ":9001"
    networks:
      - tracknest-network

  location-tracking-service:
    build:
      context: ../services/location-tracking-service
      dockerfile: Dockerfile
    ports:
      - "15000:15000"
    networks:
      - tracknest-network
    environment:
      ACTIVE_ENV: container

  ### IAM SERVICE ###
  keycloak-postgres:
    image: postgres:latest
    container_name: keycloak-postgres
    environment:
      POSTGRES_USER: postgresadmin
      POSTGRES_PASSWORD: postgresadmin
      POSTGRES_DB: KEYCLOAK
    ports:
      - "8000:5432"
    volumes:
      - keycloak-postgres-data:/var/lib/postgresql/data
    networks:
      - tracknest-network

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak
    ports:
      - "127.0.0.1:8080:8080"
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL_HOST: keycloak-postgres
      KC_DB_URL_PORT: 5432
      KC_DB_URL_DATABASE: KEYCLOAK
      KC_DB_USERNAME: postgresadmin
      KC_DB_PASSWORD: postgresadmin
    command: start-dev
    networks:
      - tracknest-network

volumes:
  criminal-info-minio-data:
  criminal-info-postgres-data:
  location-tracking-minio-data:
  location-tracking-postgres-data:
  keycloak-postgres-data:

networks:
  tracknest-network: