apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-web
  labels:
    app: web
spec:
  replicas: {{ .Values.web.replicaCount }}
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: web
          image: "{{ .Values.web.image.repository }}:{{ .Values.web.image.tag }}"
          imagePullPolicy: IfNotPresent

          ports:
            - containerPort: {{ .Values.web.port }}

          env:
            - name: NODE_ENV
              value: "production"

          livenessProbe:
            httpGet:
              path: /
              port: {{ .Values.web.port }}
            initialDelaySeconds: 60
            periodSeconds: 30

          readinessProbe:
            httpGet:
              path: /
              port: {{ .Values.web.port }}
            initialDelaySeconds: 60
            periodSeconds: 30