redis:
  enabled: true
  architecture: replication
  auth:
    enabled: true
    password: "redis-admin"
  master:
    count: 1
  replica:
    replicaCount: 1
    kind: StatefulSet

kafka:
  replicaCount: 1
  zookeeper:
    enabled: true
    replicaCount: 1
  auth:
    enabled: false
  service:
    type: ClusterIP
    port: 9092
  persistence:
    enabled: true
    size: 1Gi
  config:
    log.retention.hours: 168
    log.retention.bytes: 1073741824
    log.segment.bytes: 1073741824
    auto.create.topics.enable: true
  listeners:
    client:
      protocol: PLAINTEXT
    interbroker:
      protocol: PLAINTEXT
    auto:
      create:
        topics:
          enable: true
  controller:
    replicaCount: 1
  metrics:
    kafka:
      enabled: true
    jmx:
      enabled: false

apisix:
  apisix:
    deployment:
      role: traditional
      role_traditional:
        config_provider: yaml

    admin:
      enabled: true
      enable_admin_ui: true
      credentials:
        admin: edd1c9f034335f136f87ad84b625c8f1
        viewer: 4054f7cf07e344346cd3f287985e76a2

  etcd:
    enabled: false

  ingress-controller:
    enabled: true
    config:
      provider:
        type: apisix-standalone
    apisix:
      adminService:
        name: track-nest-apisix-admin
        namespace: dev
    gatewayProxy:
      createDefault: true
      provider:
        type: ControlPlane
        controlPlane:
          auth:
            type: AdminKey
            adminKey:
              value: edd1c9f034335f136f87ad84b625c8f1    

minio:
  enabled: false
  mode: standalone
  rootUser: "minioadmin"
  rootPassword: "minioadmin"
  persistence:
    enabled: false
  resources:
    requests:
      cpu: 10m
      memory: 64Mi

elasticsearch:
  enabled: true
  replicas: 1
  minimumMasterNodes: 1
  resources:
    requests:
      cpu: 250m
      memory: 64Mi
    limits:
      cpu: 500m
      memory: 128Mi
  volumeClaimTemplate:
    accessModes: [ "ReadWriteOnce" ]
    resources:
      requests:
        storage: 1Gi

usertracking-database:
  enabled: false
  auth:
    username: "database-admin"
    password: "database-admin"
    database: "tracknest"

emergencyops-database:
  enabled: false
  auth:
    username: "database-admin"
    password: "database-admin"
    database: "tracknest"

criminalreports-database:
  enabled: false
  auth:
    username: "database-admin"
    password: "database-admin"
    database: "tracknest"

iam-database:
  enabled: false
  auth:
    username: "database-admin"
    password: "database-admin"
    database: "tracknest"

iam:
  enable: false
  image: "nguyenvu04/track-nest.iam:dev"
  dbVendor: "postgres"
  dbUsername: "database-admin"
  dbPassword: "database-admin"
  dbUrl: "jdbc:postgresql://iam-database.dev:5432/tracknest"

usertracking:
  enable: false
  image: "nguyenvu04/track-nest.user-tracking:dev"

criminalreports:
  enable: false
  image: "nguyenvu04/track-nest.criminal-reports:dev"

emergencyops:
  enable: false
  image: "nguyenvu04/track-nest.emergency-ops:dev"