web:
  replicaCount: 1
  port: 3000

  image:
    repository: nguyenvu04/tracknest-web
    tag: "v1.2.8"
    pullPolicy: IfNotPresent

  nodeEnv: production
  nextPublicUserTrackingApiUrl: "https://api.tracknestapp.org/user-tracking"
  nextPublicEmergencyOpsApiUrl: "https://api.tracknestapp.org/emergency-ops"
  nextPublicCriminalReportsApiUrl: "https://api.tracknestapp.org/criminal-reports"
  nextPublicKeycloakUrl: "https://tracknestapp.org/auth"

  resources:
    requests:
      cpu: "100m"
      memory: "128Mi"
    limits:
      cpu: "200m"
      memory: "256Mi"

  podSecurityContext:
    runAsNonRoot: true
    runAsUser: 1000
    fsGroup: 1000
    seccompProfile:
      type: RuntimeDefault

  containerSecurityContext:
    allowPrivilegeEscalation: false
    readOnlyRootFilesystem: false
    capabilities:
      drop: ["ALL"]

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0

  revisionHistoryLimit: 5
  terminationGracePeriodSeconds: 30

  probes:
    liveness:
      path: /
      initialDelaySeconds: 60
      periodSeconds: 30
      timeoutSeconds: 5
      failureThreshold: 3
    readiness:
      path: /
      initialDelaySeconds: 30
      periodSeconds: 10
      timeoutSeconds: 5
      failureThreshold: 3

  hpa:
    enabled: false
    minReplicas: 1
    maxReplicas: 3
    targetCPUUtilizationPercentage: 75

  pdb:
    enabled: false
    minAvailable: 1
